### ISSUE TITLE
Comma in tag in sidecar during import causes truncation of tag

### ISSUE THREAD

**Issue by Cat333Pokemon** [darktable-org/darktable#11666]
**Describe the bug/issue**

Importing a photo with a sidecar XMP file with a comma in a tag causes the tag to be truncated to only the data before the tag. This also deletes any nested tags.

For example, `<rdf:li>animal|bird|Sandpipers, Phalaropes, and Allies|Wilson's Snipe</rdf:li>` becomes `<rdf:li>animal|bird|Sandpipers</rdf:li>` after import.

**To Reproduce**
1. Ensure "write sidecar for each image" is enabled in the settings.
2. Add a tag to a photo where one of the tags contains a comma.
3. Copy the photo and XMP file to another computer or instance of Darktable.
4. Import the photo.
5. Inspect the tags associated with the photo as well as the XMP file alongside the photo.
6. The tag should be truncated.

**Expected behavior**
The tag should import without truncation.

**Screenshots**
![tags](https://user-images.githubusercontent.com/47996040/165634616-619504aa-8dd9-4672-9c14-848673a34b6a.png)

**Platform**
* darktable version : 3.0.1
* OS                : Linux kernel 5.4.0-109-generic
* Linux - Distro    : Mint 20.3 
* Memory            : 16 GB
* Graphics card     : NVidia GeForce GTX 1060 3 GB
* Graphics driver   : 510.60.02
* OpenCL installed  : No
* Xorg              : 7.7+19ubuntu14
* Desktop           : Cinnamon 5.2.7
* gcc               : 9.4.0

**Comment by Cat333Pokemon** [comment]
I realized my Darktable version was quite out of date, added the repository, updated to 3.8.0, and the issue still occurs.

**Comment by elstoc** [comment]
Are you able to update to 3.8.1? I remember quite a few tagging issues being resolved in 3.8.1.

**Comment by Cat333Pokemon** [comment]
I backed up my `.config/darktable` folder and deleted it before trying each `3.8.1-1.1_amd64` and `3.9.0~git1346.5849f277-1_amd64` via the binary .deb packages, then I verified the contents of the XMP file before importing the photo into the library. No differences in behavior.

**Comment by michal-n** [comment]
I run Darktable 4.0.0 on Ubuntu 22.04 (from OBS) and it looks like this is still present.
Package version: 4.0.0-1.1_amd64.
