### ISSUE TITLE
HLR segmentation based: weird segmentation masks in combination with waveform/parade mode histogram

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#12913]
depending on the combination settings the masks shows different colored artifacts:
![image](https://user-images.githubusercontent.com/39386816/202015742-1255457d-8caf-423d-bf76-d568a381d1b1.png)
switching mask on off several times can change those strange artifacts; sometimes no artifacts, sometimes the color changes

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. open segmentation based hlr
2. Click on mask for segments
3. see artifacts; if not do it some further times

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version :  darktable 4.1.0+1016~g0a9aca6b7-dirty
* OS                : OSx

**Comment by jenshannoschwalm** [comment]
@MStraeten i think the pr should fix this.

There is one thing i am irritated about - you mentioned a "combination setting". If you change one of the visualizing mask  buttons, all other buttons should be off. Is that correct on your system?

**Comment by MStraeten** [comment]
unfortunately not fixed - but maybe osx display resolution (internal retina and external WQHD) related stuff since i haven't seen that with my windows build yet.

just one mask is active. but changing the value for "combine" using the slider shows different artifacts for different values but also different artifacts for one value if thats set again, sometimes no artifacts
also visible with "candidating" but never with "clipping threshold"

**Comment by jenshannoschwalm** [comment]
Now I have no clu. Could you make a video?

**Comment by MStraeten** [comment]
issue is present with and without OpenCL
https://user-images.githubusercontent.com/39386816/202370159-936e9394-3849-4882-9e9e-20d6cf05fb62.mp4
will make some further investigations later

**Comment by jenshannoschwalm** [comment]
Ok i see. BTW i was also able to reproduce some "strange output", will investigate further

**Comment by MStraeten** [comment]
after some further investigations startiong with a clean cache and darktablerc it breaks in dependence of the histogram setting:
I can reproduce the issue by switching the histogram to waveform or parade (but only with macos)

**Comment by MStraeten** [comment]
sample showing the different behaviour depending on histogram mode see https://github.com/darktable-org/darktable/pull/12931#issuecomment-1321076780

**Comment by geni1105** [comment]
Could not reproduce on iMac 27'' Retina, late 2014, macOS Big Sur 11.7 with macOS build 4.1.0+1066~gcb5cb3736 ...

Tried different images, "combine" slider values, histogram settings and switched combine mask on/off dozens of times. Sames with the other masks.

**Comment by TiredOfGuessing** [comment]
I was just about to report I could not produce it, when I produced it. I took an over exposed image of morning clouds. I was viewing at 100%. I played around with the various data displays (histo, scope, parades) changing exposure, then highlight reconstruction method = segmentation based, adjusting the sliders and turning the masks off/on, changing rebuild setting, after multiple iterations everything was fine. I started typing this then went back to highlight reconstruction and reset the highlight reconstruction module via circle icon, clicked on the candidating mask, then the combine mask and it happened. Resetting the view scale resolved the rendering issue, there are no immediate signs of corruption other than the rendering. 

This was using @MStratten’s Intel build running on an Macbook with M1 chip and Rosetta2 translation, macOS 13.0.1 Ventura. I renamed the previous .config/darktable folder so a clean install in that regard. I realize this is somewhat convoluted since the code is a translated binary, but it also means the operations were translated with the same effect. Hope this helps. If I can do more let me know. I have not gotten to compiling dt yet and don’t know much about the internals. 

![HLR](https://user-images.githubusercontent.com/105315850/204100990-6ed98274-604a-44e7-87f8-1aa0e160212d.jpg)

**Comment by jenshannoschwalm** [comment]
@MStraeten  could you please recheck this with current master?

1. without any special flags
2. with --disable-pipecache

I hope i understand the problem now, If my hypothesis is correct you shouldn't have the issue with test_2

**Comment by MStraeten** [comment]
current master noflags:

https://user-images.githubusercontent.com/39386816/230469238-9085dd9d-997f-482f-9a96-33f1fa2fbe9a.mp4

master --disable-pipecache:

https://user-images.githubusercontent.com/39386816/230469756-7e9684ea-428f-46f1-bd5e-b8692ab5f027.mp4

master + 14130:

https://user-images.githubusercontent.com/39386816/230470570-22a3b28c-66fb-41e3-9291-e5e9e67bb068.mp4

**Comment by jenshannoschwalm** [comment]
Thanks. So that's still another issue.
Could you send a log with -d pipe?

**Comment by MStraeten** [comment]
[log_14130-d_pipe.txt](https://github.com/darktable-org/darktable/files/11176106/log_14130-d_pipe.txt)

**Comment by jenshannoschwalm** [comment]
Thanks a lot. For me the caching thing looks correct, i am pretty surprised about the `[segmentize_plane] 1750x1170 number of segments exceeds maximum=4711` log.
