### ISSUE TITLE
Can't build darktable on Fedora 37

### ISSUE THREAD

**Issue by indy07cz** [darktable-org/darktable#12939]
Hi, I'm not able to build darktable development snapshot on new Fedora 37.  Master/stable version works fine. See error below.
`[ 97%] Built target channelmixerrgb
/home/janholl/Downloads/darktable/src/imageio/format/jxl.c: In function ‘write_image’:
/home/janholl/Downloads/darktable/src/imageio/format/jxl.c:196:3: error: unknown type name ‘bool’
  196 |   bool write_color_natively = true;
      |   ^~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [lib64/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/build.make:76: lib64/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/jxl.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6589: lib64/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
`

* darktable version : 8a83c785cd875d0c844c342510f82de72757f7ea
* OS                : Linux-kernel 6.0.8-300.fc37.x86_64
* Linux - Distro    : Fedora 37
* Memory            : 
* Graphics card     :  AMD Ryzen 5 2400G with Radeon Vega Graphics
* Graphics driver   : amdgpu
* OpenCL installed  : yes
* OpenCL activated  : no
* Xorg              : 22.1.5
* Desktop           : wayland (Gnome 43)
* GTK+              : 3.2.34
* gcc               : 12.2.1
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by TurboGit** [comment]
Should be fixed.

**Comment by indy07cz** [comment]
Still get this:
`[ 97%] Linking C shared module libchannelmixerrgb.so
/home/janholl/Downloads/darktable/src/imageio/format/jxl.c: In function ‘write_image’:
/home/janholl/Downloads/darktable/src/imageio/format/jxl.c:250:30: error: ‘false’ undeclared (first use in this function)
  250 |       write_color_natively = false;
      |                              ^~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [lib64/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/build.make:76: lib64/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/jxl.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6589: lib64/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
`
Version: 7ce274f7528a3072db610c9f9717856120b1bf4d

**Comment by TurboGit** [comment]
Should be fixed :)

**Comment by indy07cz** [comment]
Yes, it works. Thx :)
