### ISSUE TITLE
dt 4.2: Ctrl+t not working for tagging

### ISSUE THREAD

**Issue by mlaverdiere** [darktable-org/darktable#13180]
I'm on darktable 4.2.0, freshly upgraded, on Fedora 37 (GNOME 43.2, with default Wayland) using OpenCl on a laptop (Asus B9450FA /Intel, i5-10310U UHD graphic).

When trying to tag photos using keyboard shortcut ctrl+tag, the usual input small box oddly appears in the upper left corner, right on the window title bar (instead of bottom centre), and it is just not working. Trying to put some text as tag does nothing. See screenshot attached.

My tests were made with a fresh darktable setup, with all the default settings (except for dark theme, to make it more clear for the screenshot).

![Dessin sans titre](https://user-images.githubusercontent.com/30075133/209140850-db5b705f-5c56-4315-b938-5fc381c50b96.jpg)

**Comment by gi-man** [comment]
Please use the template to provide all the relevant information. I'm assuming you are on Gnome using Wayland. 

I can reproduce on Fedora 37 KDE Wayland, but not on x11.

**Comment by TurboGit** [comment]
Probably Wayland related then as I do not reproduce on Xorg. That's not really urgent as at the moment there is no color management on Wayland so it is not a proper layer for retouching photo.

**Comment by dterrahe** [comment]
Sounds similar to #12478/#12484.

**Comment by mlaverdiere** [comment]
Yes, after some more testing, seems to be a Wayland issue.

For those like me who want to stay under Wayland (default on Fedora and Ubuntu, among others)  while we wait for the bug to be fixed, the workaround could be to start darktable with this command: 

GDK_BACKEND=x11 darktable

**Comment by Nilvus** [comment]
Some Wayland issues should so probably be fixed by now by reverting that commit https://github.com/darktable-org/darktable/commit/41948c9514e1a0a060a01ea8afc1046700e18dc7
Maybe was too early to put back native Wayland. Said that, the best fix for Wayland users remains to use X11 for such software, Wayland do not have any color management support and it's a bad thing for such software.

**Comment by mlaverdiere** [comment]
Bug still present on 4.2.1 (not surprisingly since it was removed from 4.2.1 milestone).

**Comment by Nilvus** [comment]
> Bug still present on 4.2.1 (not surprisingly since it was removed from 4.2.1 milestone).

This will not disappear if nobody spent time to fix it. Devs use mostly X11 as Wayland do not have complete proper color management and so not actually recommended to use.

**Comment by mlaverdiere** [comment]
I understand the color management issue with Wayland, but I don't recall having read that it was not recommended to use it with darktable, including in the current documentation (I may have missed something?). Anyway, considering that some major distros default to Wayland, it means that currently darktable si not working properly out of the box for many users, for a not so trivial tag (keyword) management feature... 

So my suggestion would be that either we assume that darktable supports Wayland and a fix should be considered for ctrl+t to work on Wayland, or otherwise, we assume that darktable doesn't not support wayland and, like previously proposed, it would probably be better if dartable was starting in X11 (xWayland) mode, so ctrl-t would work properly (by reverting that commit: https://github.com/darktable-org/darktable/commit/41948c9514e1a0a060a01ea8afc1046700e18dc7

And of course, I understand that in either case, it's up to a dev to decide if he/she wants to spend time on this. This is just a bug report!

**Comment by ptilopteri** [comment]
it is long standing recommendation and comment that wayland was a poor or unusable choice for using darktable.  accessing darktable.org and searching for wayland will provide you with some instances.  that you fail to invest some minimal effort researching does allow you to make unfounded comments better unsaid.  you are welcome to assist in making wayland usable for color management but that is not the darktable developers job.  it is a volunteer  effort as is most open software and those interested in a particular feature provide what they feel *they* need, not what you prefer.  continued ranting will definitely not change that.  ball is in your court!

**Comment by dterrahe** [comment]
I don't think there's anything wrong with the way this bug was reported or the request to default to xwayland. To me it makes sense to avoid surprises and there's no (?) benefit to running on "native" Wayland.

**Comment by victoryforce** [comment]
> it is long standing recommendation

Where does it stand?

> unfounded comments better unsaid

Sorry @ptilopteri, but your comment is totally out of line.

**Comment by dterrahe** [comment]
No need to escalate :-)

I think the simple solution is just for someone to submit a PR reversing commit 41948c9
I'm on my phone right now; Victor would you be willing to pick this up?

**Comment by victoryforce** [comment]
> No need to escalate :-)

Agreed. 🙂

> I think the simple solution is just for someone to submit a PR reversing commit 41948c9 I'm on my phone right now; Victor would you be willing to pick this up?

OK. Preparing PR...

**Comment by Nilvus** [comment]
@ptilopteri: my comment was only to explain why Wayland bug are not fixed actually, not debate about that.

Thanks @dterrahe and @victoryforce for your proposal. I think it's better to revert that commit. This one was done too early. Maybe we can also close with your PR, @victoryforce, other Wayland issues? We can found them with depends:wayland label.

**Comment by victoryforce** [comment]
> Thanks @dterrahe and @victoryforce for your proposal. I think it's better to revert that commit. This one was done too early. Maybe we can also close with your PR, @victoryforce, other Wayland issues? We can found them with depends:wayland label.

Thanks. Linked these issues to PR.
