### ISSUE TITLE
Panasonic LX7 garbage pixels

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#14082]
**Describe the bug/issue**
Some LX7 images have garbage pixels on the edge. The affected files, when processed using dcraw, have no garbage data.

**To Reproduce**
1. Download the files from https://tech.kovacs-telekes.org/files/2023-04-01-lx7-garbage-pixels/
2. Import and open them in the darkroom.
3. Check for garbage on the right

**Expected behavior**
No garbage pixels.

**Screenshots**
2023-03-30_17-06-32_P1000043.RW2
No garbage pixels - size shown in _image information_: 3792 (3920) x 2536:
![image](https://user-images.githubusercontent.com/3177739/229275418-fd2baaca-a105-4185-bb61-92cd4e23b431.png)
Camera's JPG: 3776 x 2520
dcraw PPM: 3792 x 2536

2023-03-30_17-06-32_P1000044.RW2
Garbage pixels - size shown in _image information_: 3792 (3920) x 2476:
![image](https://user-images.githubusercontent.com/3177739/229275472-ed755a8a-7c42-4838-98a7-a447c3f9578e.png)
Camera's JPG: 3776 x 2520
dcraw PPM: 3704 x 2476

Images sizes from camera manual:
Aspect ratio 4:3 -> 3648 x 2736
Aspect ratio 3:2 -> 3776 x 2520
Aspect ratio 16:9 -> 3968 x 2232
Aspect ratio 1:1 -> 2736 x 2736

**Additional info**
I had optical zoom set to maximum; I may have accidentally slipped into the digital zoom range with the corrupted image. I've tried taking images with digital zoom to verify, but have been unable to reproduce the issue.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.3.0+1501~gf103dd65ab
* OS                : Linux 5.19.0-38
* Linux - Distro    : Ubuntu 22.10
* Memory            : 64 GB
* Graphics card     : NVidia 1060/6GB
* Graphics driver   : 470.161.03
* OpenCL installed  : yes
* OpenCL activated  : yes/no (tested both)
* Xorg              : 7.7+23ubuntu2
* Desktop           : KDE Plasma 5.25.5-0ubuntu1
* GTK+              : 3.24.34-3ubuntu2
* gcc               : 12.2.0-3ubuntu1
* cflags            : N/A
* CMAKE_BUILD_TYPE  : Release

**Comment by kofa73** [comment]
The garbage pixels correspond to the area extending over the 3:2 crop set in the camera. Two columns are visible: one seems to be repeated image data; the other, garbage:
![image](https://user-images.githubusercontent.com/3177739/229276600-ed221b76-f7d5-4003-90f0-6f36c0a0a035.png)

**Comment by kmilos** [comment]
I cannot reproduce using https://raw.pixls.us/ samples (in any of the 4:3, 3:2, 16:9 nor 1:1 modes) and dt 4.2.1 on Windows.

The default crop for 3:2 is e.g.

![image](https://user-images.githubusercontent.com/4973094/229484933-df9cbea5-3f7e-4920-932b-41212f933aa3.png)

**Comment by kofa73** [comment]
It does not occur with all files. It may have something to do with digital zoom, as the LX7 _crops the raw image_ if you use digital zoom. As an example, an image of a map was over 10 MB without digital zoom, and only 3.2 MB with maximum digital zoom.

**Comment by kmilos** [comment]
Perhaps try resetting the rawprepare ("raw black/white point") module?

You can also switch `plugins/darkroom/rawprepare/allow_editing_crop=false` to `true` in your user `darktablerc` and then verify the crop settings in the rawprepare module are as expected (compare to cameras.xml).

**Comment by kmilos** [comment]
> As an example, an image of a map was over 10 MB without digital zoom, and only 3.2 MB with maximum digital zoom.

Ah, that could make sense, cameras.xml and rawprepare would not know how to handle that. Your best bet is to enable that hidden option then and adjust the rawprepare crop manually...

**Comment by kofa73** [comment]
> > As an example, an image of a map was over 10 MB without digital zoom, and only 3.2 MB with maximum digital zoom.
> 
> Ah, that could make sense, cameras.xml and rawprepare would not know how to handle that.

Actually, they do (something does, anyway). Here is the image info with a maximally zoomed-in image:

![image](https://user-images.githubusercontent.com/3177739/229565518-1efb7491-f479-4e36-8661-7284e44cecf2.png)

rawprepare's crop setting:
![image](https://user-images.githubusercontent.com/3177739/229566120-40341e79-80a4-46e3-9859-b064f001c812.png)

For the garbled image, 2023-03-30_17-06-32_P1000044.RW2, the correct value for the right crop seems to be 214.

**Comment by kmilos** [comment]
> Actually, they do (something does, anyway).

It comes from the code snipped I linked to. For those values it grabs the 16:9 no-zoom setting from cameras.xml:

https://github.com/darktable-org/rawspeed/blob/bd03fd4878b5296d1f35cf40e554cfcff131bdb4/data/cameras.xml#L10333

**Comment by jsmucr** [comment]
This shows once again that the whole rawspeed idea of supplying the *biggest possible images* does not make much sense. Issues such as this one will never be entirely solved without an architectural change.

**Comment by jsmucr** [comment]
https://github.com/darktable-org/rawspeed/pull/490

**Comment by kmilos** [comment]
@kofa73 @jsmucr This should now be working in master, can you please confirm?

**Comment by kofa73** [comment]
Unfortunately it's still failing for 2023-03-30_17-06-32_P1000044.RW2.
4.5.0+1219~geb2d8420a0
![image](https://github.com/darktable-org/darktable/assets/3177739/82bae3be-f3d8-438b-bb80-2c1e580cb531)

**Comment by kmilos** [comment]
How about removing the crop lines for LX7 from cameras.xml?

**Comment by kofa73** [comment]
Thanks! The garbage is gone if I remove the crop lines.

**Comment by kmilos** [comment]
Thanks for checking. How does it affect normal files w/o digital zoom? Does it change the expected crop considerably?

**Comment by kofa73** [comment]
I tried a wide-angle shot I exported earlier and now with current master + crop lines removed; the image changed by a few pixels only (I'm not exactly sure if it was the same stack).
Resetting rawprepare cropped in 8 pixels from all sides, so not an issue.
I cannot test more today. Post here if you want me to test more (aspect ratios etc.).

**Comment by kmilos** [comment]
Sounds like it's safe to make the change - old edits are preserved, the difference on new ones seems small enough.

**Comment by LebedevRI** [comment]
@kofa73 could you please contribute one such problematic sample to RPU?

**Comment by kofa73** [comment]
I've uploaded some (all aspect ratios with full "intelligent zoom" - Panasonic uses the term "digital zoom" when they don't just crop, but also enlarge the middle parts of the image).
Interestingly, some aspect ratios used to have artefacts when "intelligent zoom" was used partially (not at maximum zoom), but not when fully "zoomed in".
With the crop-lines removed (using vendor crop), I do not get any issues anymore. A pleasant surprise is that with some aspect ratios, I actually get more visible image surface with the crop-lines removed. E.g. with the aspect ratio 3:2, the cropped (i-zoomed) raw is 1904x1276 px (1.492 : 1); the old darktable crop was 1776x1276 (1:39 : 1, more like 4:3 than 3:2) (0, 0, 128, 0 for left, top, right, bottom crop); with the vendor crop, I get 1888 x 1260 (1.498 : 1) (8 px from all sides; all clear -- and I could even set 0 for all sides, there is no garbage at all).

**Comment by LebedevRI** [comment]
@kofa73 thank you for contributing the samples!
