### ISSUE TITLE
Quirks in `module order` appearance

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#14409]
### Describe the bug

Recent changes to autoselect `module order` depending on image type, i.e RAW vs JPG, seems to work as expected.

However, there seems to be some quirks in the user interface.

Normally it looks like this:
 ![ss1](https://user-images.githubusercontent.com/12815378/236060513-bfb6d430-04c8-4bb6-8ef8-20decd1bdd62.png)

but occasionally it turns into this:
![ss2](https://user-images.githubusercontent.com/12815378/236060606-c42a1841-32f8-4c55-b066-86ff37e0fb3b.png)

and the following errors are shown:
```
(darktable:15772): CRITICAL **: 17:56:00.831: dtgtk_expander_get_header: assertion 'DTGTK_IS_EXPANDER(expander)' failed

(darktable:15772): Gtk-CRITICAL **: 17:56:00.831: gtk_box_pack: assertion 'GTK_IS_BOX (box)' failed

(darktable:15772): Gtk-CRITICAL **: 17:56:00.831: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
```

### Steps to reproduce

I think I can reproduce the behavior with these steps:
- open an image in darkroom: `module order` is shown correctly
- do some edits, e.g. change exposure
- go back to lightroom
- history stack -> discard history
- go back to darkroom : `module order` is shown differently and errors appear in the console

### Where did you install darktable from?

OSB

### darktable version

4.3.0~git2127.3ecec6d7-314.1

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Tumbleweed

### Are you using OpenCL GPU in darktable?

None

**Comment by ansluk** [comment]
I think this is the same as #14261

**Comment by TurboGit** [comment]
I have been able to reproduce only:

`(darktable:15772): Gtk-CRITICAL **: 17:56:00.831: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed`

And this is now fixed. Can you double check that all is ok on your side? TIA.

**Comment by pehar1** [comment]
Also only could reproduce the error message

`gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed`

but not the described issue regarding the module order (screenshots). @TurboGit your patch fixes the error message.

**Comment by lbilli** [comment]
On my end, the third error is also gone.

However, the other two errors and the change in appearance still happen when following the steps above.
Moreover, on rare occasions dt crashes when discarding history.

[darktable_bt_OMCC41.txt](https://github.com/darktable-org/darktable/files/11397462/darktable_bt_OMCC41.txt)

**Comment by ansluk** [comment]
I can reproduce this on Ubuntu 23.04 with glib 2.76.1. I belive it's related to the failed call to ioporder.c:update from lighttable in #14261 . As a test I commented out raising DT_SIGNAL_DEVELOP_IMAGE_CHANGED in imagec:dt_image_update_final_size and it fixes the module order label for me.

**Comment by TurboGit** [comment]
@ansluk @lbilli @pehar1 : Can you test the new PR #14416? TIA.

**Comment by ansluk** [comment]
PR #14416 Fixes the module order label issue on Ubuntu 23.04 for me. It also fixes the problems I had with segfaults when duplicating in lighttable on a windows msys build mentioned in #14261 . Thanks!

**Comment by TurboGit** [comment]
@ansluk : Thanks, so I have now merged in master to get more field testing.

**Comment by lbilli** [comment]
Issue fully resolved for me too.
