### ISSUE TITLE
Labels in image information section are corrupted when user has polish language. [Windows]

### ISSUE THREAD

**Issue by wkucjas** [darktable-org/darktable#14429]
### Describe the bug

User has corrupted strings in image information section:

![bad](https://user-images.githubusercontent.com/12201900/236625907-52006f2d-de0b-460b-9d0e-96186207def6.PNG)

It looks like this is an issue in datetime.c file in dt_datetime_gdatetime_to_local function line 137 when g_date_time_format function returns corrupted string. 

![polish](https://user-images.githubusercontent.com/12201900/236626081-b9a13a18-426e-4e3f-b8fb-fe1c13c1cd8f.PNG)

It might be connected with issue described here: 
https://bugzilla.gnome.org/show_bug.cgi?id=668250

When program language is set to english then everything works fine.

### Steps to reproduce

1. Start darktable with Polish language set in settings
2. Select a photo
3. Expand image information section (on the left)
4. You will notice corrupted strings everywhere where program produces dates and time.

### Expected behavior

Darktable should print labels without corrupted characters.

### Logfile | Screenshot | Screencast

![bad](https://user-images.githubusercontent.com/12201900/236626211-f22cf79b-131b-4368-9901-8d5794b289d3.PNG)
![polish](https://user-images.githubusercontent.com/12201900/236626215-7fa26cfa-ea6e-42d6-ad6b-866bf600e057.PNG)

![good](https://user-images.githubusercontent.com/12201900/236626214-10b0e643-eed4-4ed1-9a13-ddac98c2d848.PNG)
![english](https://user-images.githubusercontent.com/12201900/236626212-dc197d2a-1ba5-402f-b567-6409e13b3a3b.PNG)

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 21H2

### Describe your system?

System has set up Polish language as default.

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
Maybe fixed in current master as some changes have been done in this area, on my side on GNU/Linux:

![image](https://user-images.githubusercontent.com/467069/236638568-bcf103f4-846e-4959-8dff-aba9a6603716.png)

![image](https://user-images.githubusercontent.com/467069/236638580-60070e9a-1b85-4ba1-8ab7-fa3693b2d842.png)

![image](https://user-images.githubusercontent.com/467069/236638595-483b14cd-072b-43a6-8afa-b45da5677598.png)

**Comment by wkucjas** [comment]
> Maybe fixed in current master as some changes have been done in this area, on my side on GNU/Linux:
> 
> ![image](https://user-images.githubusercontent.com/467069/236638568-bcf103f4-846e-4959-8dff-aba9a6603716.png)
> 
> ![image](https://user-images.githubusercontent.com/467069/236638580-60070e9a-1b85-4ba1-8ab7-fa3693b2d842.png)
> 
> ![image](https://user-images.githubusercontent.com/467069/236638595-483b14cd-072b-43a6-8afa-b45da5677598.png)

I built it from master branch and i see this issue still on Windows.

**Comment by TurboGit** [comment]
So that's looks like a Windows specific issue. We need a windows dev here.

**Comment by TurboGit** [comment]
BTW, looking at your screenshot it seems that your local (or whatever it is named on Windows) is not the same as me. Or maybe that's because they where from 4.2.x? Can you post screen shots of the issues with 4.3 (current master)? TIA.

**Comment by wkucjas** [comment]
Sure, original screenshots attached to issue are from release 4.2.1. Here is from master head commit (from 3 days ago)
![obraz](https://user-images.githubusercontent.com/12201900/236639331-ba62e543-2736-428f-b3fb-ac67de8f4623.png)

**Comment by Mr-Groch** [comment]
Issue still exists in latest version (4.6.0). Can I help somehow? I'm using Polish Windows 11

**Comment by Mr-Groch** [comment]
Issue still exists in latest version (4.6.1)
