### ISSUE TITLE
[FR] Improve visibility of handles in drawn mask.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#16388]
**Is your feature request related to a problem? Please describe.**

In many of my photo edits I make a lot of use of draw masks, even several masks on a single image. Something that happens to me is that I'm over 50 years old and my eyesight is exhausted, thanks to the use of prescription glasses I can continue with my work. In my case, having a 32" 4K monitor with 3840 x 2160 resolution, I often find it difficult to select the handlers in the draw masks in the image I am working on.

**Describe the solution you'd like**

These handles are not always active, only when the mouse passes or hovers over them, so I think it wouldn't be a bad thing if, when hovering over them to make modifications, they were a little larger than they currently are.

BTW I have created a layout specifically for the gradient mask with two additional handles, the start and finish compression, this is just an idea, because when using the scroll + Shift the compression changes the values in jumps, to be more precise go to the masks manager module menu and move the compression slider then holding down the Ctrl while using the mouse scroll. It is more intuitive if you enter these two handlers because visually and more quickly you can place the compression at the point where you want. It would also have the same level of interactivity as the other handlers.

I also put two additional handlers to modify the curvature without the need to use the mouse scroll or without having to go to the masks managers module. These two handlers would work only by placing the cursor over one of them and dragging until the desired curvature is achieved.

**Alternatives**

One solution would be to introduce a new option in the configuration window in darkroom/modules with the possibility to choose the size of the handler. (I particularly would not like this option as you developers yourselves are not in favor of cluttering the configuration window with options).

But I prefer another solution, a possibility would be to put in the **global guide overlay settings** popup the option to increase the size of the handles, as it is done now with the contrast option. This option would allow users to adjust the size of the handles to their liking. 

**Additional context**

**Draw masks without displaying the masks in yellow. The rotate mask handler is almost imperceptible.**  
![Screenshot from 2024-02-26 15-41-54](https://github.com/darktable-org/darktable/assets/67672868/205ba419-e31c-42c7-acec-101635387cdc)

**Draw masks displaying the masks in yellow. The rotate mask handler is still almost imperceptible.** 
![Screenshot from 2024-02-26 15-43-15](https://github.com/darktable-org/darktable/assets/67672868/4c585ce9-873c-4c3e-a76e-34f7ea134bb2)

**Draw masks displaying the handlers bigger than the actual size (this proposal shows the additional handlers for set the compression and curvature)** 
![Screenshot from 2024-02-26 11-17-47](https://github.com/darktable-org/darktable/assets/67672868/eb3c6ac2-43d7-44d2-92a8-fec3132115ac)

**Popup menu with the option handlers size option** 
![Screenshot from 2024-02-26 16-03-22](https://github.com/darktable-org/darktable/assets/67672868/c0577572-55d2-427f-aace-796d34836e97)

**Comment by ralfbrown** [comment]
You are talking about drawn masks - parametric masks do not have any on-image controls since they compute their effect strength based on the values of each individual pixel.

**Comment by difrkaguilar** [comment]
> You are talking about drawn masks - parametric masks do not have any on-image controls since they compute their effect strength based on the values of each individual pixel.

Corrected the error. Thanks.

**Comment by zisoft** [comment]
We had the sampe problem recently on macOS, where the OS always reports 72 DPI.
It was fixed with #15845

**Comment by zisoft** [comment]
#15845 was a macOS specifix bugfix.

@difrkaguilar what is your OS?

**Comment by difrkaguilar** [comment]
> is the size issue on all kind of masks?

Every draw mask have the same issue.

![Screenshot from 2024-02-27 09-39-33](https://github.com/darktable-org/darktable/assets/67672868/f076ed71-64a1-43c4-9fba-240688860112)

> what is your OS?

OS: Fedora workstation release 37 (Thirty Seven) x86_64

**Comment by difrkaguilar** [comment]
This is the screenshot of the screen and the `fit view` of darkroom. Screen resolution 3840 x 2160 (16:9) scale 100%
![Screenshot from 2024-02-27 11-09-11](https://github.com/darktable-org/darktable/assets/67672868/7b638776-556d-4bef-9d83-ece7d8082348)

**Comment by difrkaguilar** [comment]
I changed the scaling factor to 1.30
![Screenshot from 2024-02-27 11-48-45](https://github.com/darktable-org/darktable/assets/67672868/a2f95d5c-079c-4fdf-a3a2-76b947b9b404)

But now the text is big too.
![Screenshot from 2024-02-27 11-49-11](https://github.com/darktable-org/darktable/assets/67672868/780166b3-6704-48be-bc31-518d6c51f4ca)

**Comment by difrkaguilar** [comment]
screen_dpi_overwrite=-1.000000

**Comment by gi-man** [comment]
Are you using Wayland? I think that screen is to scale the font, but what happens if you scale the screen display?

**Comment by difrkaguilar** [comment]
> Are you using Wayland?

X11 no Wayland.

**Comment by gi-man** [comment]
And what happens when you scale the display?

**Comment by difrkaguilar** [comment]
> And what happens when you scale the display?

The handlers increase their size a bit, but the whole system increase the windows and everything become a mess.

![Screenshot from 2024-02-28 09-07-33](https://github.com/darktable-org/darktable/assets/67672868/1a998d29-8afb-4e8b-a49f-f0d6035f27b9)

This is an screenshot of the desktop. I scaled the display to 200% but have to set the Scaling Factor to 0.8 for the fonts. Anyway this is not an option for me, I use Blender and other apps and need screen space.
![Screenshot from 2024-02-28 09-09-13](https://github.com/darktable-org/darktable/assets/67672868/9eb3405f-0cc9-4fe6-81a2-6aeacaec380d)

This is an screenshot of Blender at 3840 x 2160
![Screenshot from 2024-02-28 09-27-59](https://github.com/darktable-org/darktable/assets/67672868/9b7c7db3-729a-4c23-b5f5-fe2cd9e8d3d5)

**Comment by gi-man** [comment]
Gnome only lets you pick 200%. I'm in fedora KDE and I pick fractional (125%).

**Comment by difrkaguilar** [comment]
> Gnome only lets you pick 200%. I'm in fedora KDE and I pick fractional (125%).

That's good to know. But I use Gnome. I think I'm not the only darktable user with this problem. The vertex (vectors) or handles in some applications I think can be adjusted to different scales, not depending on the system, window manager or scale factor but by the applications if it's possible.

**Comment by difrkaguilar** [comment]
> What if you set `screen_dpi_overwrite` to 72 in darktablerc?

I'll try this ASAP when return to home. Then I'll see and comment about it. Thanks.

**Comment by zisoft** [comment]
> What if you set screen_dpi_overwrite to 72 in darktablerc?

The screen dpi is used to calculate the `gui->dpi_factor` by dividing the screen dpi by 96.
72 is the value macOS reports for the screen dpi, causing all GUI elements being shrinked by factor a of 0.75  (72/96) (fixed by #15845)

So setting `screen_dpi_overwrite` to a value > 96 should do the trick.

**Comment by difrkaguilar** [comment]
Set `screen_dpi_overwrite` to 72 or 96 in darktablerc doesn't fix the issue. So I'll continue working with handlers as they are now.

**Comment by difrkaguilar** [comment]
Excuse my lack of knowledge about programming, a series of functions that for some seem simple, I know that it is far from being so. I don't know the amount of code that is behind the visualization to draw these masks, but it must be quite complex.

It must be recognized that darktable's gradient mask drawing system is even more powerful than the possibilities of gradients that graphic design programs have, for example Inkscape, where it is not possible to make a bend to the gradient, but darktable's gradient masks allow it.

Reading a post similar to this one about the possibility of improving the drawing of gradient masks #14728 I make a proposal from my point of view of how the drawing of gradient masks could work in a more effective way than the one used right now.

The handlers that I describe here can further enhance the use of these gradient masks, giving more control to the user when positioning these masks in a finer way.

The mask start and end handlers can allow you to change the compression of the mask by dragging and dropping the mouse. Likewise, the handlers located in the central line could allow to bend the line until the desired position is achieved. And the handlers at the ends can make the position of the gradient mask more precise by being able to move indistinctly.

To this mask could be put the possibility of using in reverse, also as discussed in #14728 put two position controls at both ends of the center line, would allow to locate these points more accurately.

This is just an idea. Anyway I make this feature request in case there is any developer interested in implementing it or making other modifications.

**Screenshot of the gradient draw mask.**

![gradient](https://github.com/darktable-org/darktable/assets/67672868/155bc0b7-5ef8-4a4a-9d23-76fc176dbdc6)

**Screenshot of the gradient draw mask in reverse position.**

![gradient_01](https://github.com/darktable-org/darktable/assets/67672868/27550703-a994-4d1f-a463-c64fe72a9aa3)

**Comment by Mark-64** [comment]
DT 4.6.1 on Windows 11, 4k display
Scaling of mask handles looks correct to me.

![immagine](https://github.com/darktable-org/darktable/assets/43290988/fd05093e-caf8-452b-8e34-0e31b04d4a9b)

**Comment by difrkaguilar** [comment]
darktable 4.7.0~git651.e458f34f-11391.1

Then the issue must be on my side, I don't know why.
This is an screenshot at 3840 x 2160

![Screenshot from 2024-03-03 14-56-57](https://github.com/darktable-org/darktable/assets/67672868/ada1c2d1-f62e-44ac-8d8b-853040b4562e)

**Comment by zisoft** [comment]
@difrkaguilar  Do you have the possibility to compile and debug dt yourself?

If so, can you set a breakpoint in `src/gui/gtk.c` at line 1434:

https://github.com/darktable-org/darktable/blob/e458f34f45138f19c379fcd8945abcdc7068f65b/src/gui/gtk.c#L1422-L1443

and see, what value `gui->dpi` gets.

**Comment by difrkaguilar** [comment]
> Do you have the possibility to compile and debug dt yourself?

I don't have to much skills but I'll try to do my best.

**Comment by difrkaguilar** [comment]
> Do you have the possibility to compile and debug dt yourself?

Ups... I tried but I don't have the skills to do those changes. So I'll have to continue working with draw masks as they are now. My fault. Thanks anyway to all for your attention and comments.
