### ISSUE TITLE
Crashes in context of copy/paste

### ISSUE THREAD

**Issue by anoderay** [darktable-org/darktable#19612]
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

When editing photos darktable tends to crash either directly after copy/pasting settings or some time afterwards. It will hang for 10-15 sec. then crash to desktop. 

### Steps to reproduce

Edit some images, copy and paste some settings (either regularily or selective copy and paste)

### Expected behavior

not crash

### Logfile | Screenshot | Screencast

I launched the appimage from the terminal and gathered the following:
```
/tmp/.mount_darktabPBLHP/usr/bin/../lib/libcrypto.so.3: version `OPENSSL_3.3.0' not found (required by /lib64/libssl.so.3)
Failed to load module: /tmp/.mount_darktabPBLHP/usr/lib/gio/modules/libgiolibproxy.so
Gtk-Message: 16:00:26.693: Failed to load module "colorreload-gtk-module"
Gtk-Message: 16:00:26.693: Failed to load module "window-decorations-gtk-module"
Fontconfig warning: using without calling FcInit()

** (darktable:6774): WARNING **: 16:00:51.775: atk-bridge: get_device_events_reply: unknown signature
corrupted double-linked list
Abgebrochen                (Speicherabzug geschrieben) /home/user/AppImages/darktable.appimage

```

I think "corrupted double-linked list" came up when the crash happened.

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

Darktable-5.3.0+684.gc7b5d6fc50-x86_64

### What OS are you using?

Linux

### What is the version of your OS?

Bazzite 43

### Describe your system

KDE 6.4.5

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia RTX 2060

**Comment by TurboGit** [comment]
@anoderay : Should be fixed. Thanks for reporting, this issue was difficult to find/understand!

**Comment by alikstimix** [comment]
I just rebuilt with 5.3.0 + 688  The bug is still there for me.  

debugger messages vary, these is the latest:

thread #9, name = 'worker 2', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x1)
    frame #0: 0x00007ffff79eef18 libdarktable.so`_control_write_sidecars_job_run(job=<unavailable>) at sidecar_jobs.c:79:15

and after restart the next crash gave:

thread #1, name = 'darktable', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x13649)
    frame #0: 0x00007ffff6b4e3d8 libgtk-3.so.0`___lldb_unnamed_symbol11341 + 56
libgtk-3.so.0`___lldb_unnamed_symbol11341:

**Comment by ertwroc** [comment]
Hi @TurboGit Can I somehow repair .xmp file affected by this issue? I've tried to open it in 5.4, but got segfault :(

```
** (darktable:330310): WARNING **: 13:42:31.728: atk-bridge: get_device_events_reply: unknown signature
munmap_chunk(): invalid pointer
Przerwane                  (zrzut pamięci) ./Darktable-5.4.0-x86_64.AppImage --library :memory:
```

**Comment by TurboGit** [comment]
@ertwroc : One fix is to reset the history for the affected images in lighttable.

**Comment by ertwroc** [comment]
The problem is that Darktable hangs during startup so I unable to do it.  Is there any way to do it in some other way?

**Comment by TurboGit** [comment]
If you know the id of the picture you could delete the history on database.

`DELETE FROM images WHERE id=<PUT_THE_ID_HERE>`

If you don't know the `id` but you know the **filename**, you can get the `id` with:

`SELECT id FROM IMAGES WHERE filename LIKE "<FILE_NAME_HERE>"`

Hope this helps!

**Comment by TurboGit** [comment]
@ertwroc : And make sure to backup before playing with the DB.
