### ISSUE TITLE
When zoomed in "info line" doesn't load

### ISSUE THREAD

**Issue by anoderay** [darktable-org/darktable#20018]
### Is there an existing issue for this?

- [x] I checked and did not find my issue in the already reported ones

### Describe the bug

In darkroom mode when switching between images the image information line doesnt load when the image is zoomed in enough to not show the whole image anymore. 

### Steps to reproduce

go do darkroom, ensure image information line is visible. Zoom in e.g. to 100%, switch to next photo: image information line doesn't load

### Expected behavior

darktable should always load the image information line

### Where did you obtain darktable from?

darktable.org / GitHub release

### darktable version

5.4 appimage

### What OS are you using?

Linux

### What is the version of your OS?

bazzite 43

### Describe your system

KDE Wayland

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia RTX 2060

**Comment by elstoc** [comment]
I can reproduce this on 5.4.0 (ArchLinux, XFCE, xorg), though not necessarily every time I switch images

**Comment by wpferguson** [comment]
can't reproduce on current master 5.5.0+428~g6a8320e437

**Comment by Arecsu** [comment]
Possibly fixed by #21745

**Comment by anoderay** [comment]
@Arecsu sadly not fixed. Also sometimes the buttons don't load. See here with 5.7+588. 

https://github.com/user-attachments/assets/8e168c6b-d6f2-453a-b4a2-c4265793fcc5

The buttons not loading seems to be connected to certain images; possibly ones with more processing modules enabled which take a smidgen longer to load. The info-line-thing seems more random but I could reproduce the buttons not loading with that photo fairly reliably. 

The buttons reappear when moused-over; the infoline can be coaxed to appear by e.g. applying a rating/color label (possibly because I have enabled showing those).

**Comment by Arecsu** [comment]
Hmmm this smells like some race condition. These buttons in particular that reappear when mouse over were already fixed in some other places. There is a particular event that needs to be triggered to make these buttons be properly active when a photo finishes loading. It could be that we are not triggering this, or there is a race condition by this fast photo change that makes them deactivate because of a late stale trigger. Will check this next week
