### ISSUE TITLE
Regression for reading in long icm filenames with commit b779bb6

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#2357]
**Describe the bug**
An icm profile with a long name cannot be found. Darktable reports on the command line:
[colorin] could not find requested profile `/home/foo/config/darktable/color/in/Nkx_D300_4139837_01_1_03_9_00_10_00_00_00_05_00_0400_0_0_32_47'!

You can observe that the filename is truncated and does not end with .icm. The complete filename is "Nkx_D300_4139837_01_1_03_9_00_10_00_00_00_05_00_0400_0_0_32_476_SD1.icm"

**To Reproduce**
1. place an icm profile in the color/in directory with the filename "Nkx_D300_4139837_01_1_03_9_00_10_00_00_00_05_00_0400_0_0_32_476_SD1.icm"
2. Try to apply the input color profile
3. Darktable reports on the commandline that the icm profile cannot be found. Note: The filename is truncated in the message.

**Expected behavior**
The icm profile is applied.

**Platform (please complete the following information):**
I have tried the master branch, darktable-2.6x and darktable-2.4x.

**Workaround**
If you shorten the filename darktable is able to apply the color profile without any issues.

**Additional**
I could attach the icm profile which was sent to me but I am not sure about the legal consequences (hence it is a profile extracted from a Nikon program for a Nikon D300). I can attach/send the file directly if this is necessary. I guess you can reproduce the issue on your system by copying one of your own icm profiles and make a long name.

**Commit that introduced the error**
I have bisect the code and found:

b779bb61a90d5e44cf52e51ce4ec39771fccbd5b is the first bad commit
commit b779bb61a90d5e44cf52e51ce4ec39771fccbd5b
Author: Pascal Obry <pascal@obry.net>
Date:   Thu Jan 31 16:52:30 2019 +0100

    colorspaces: store full pathname to be able to check existence.
    
    Fixes #12576.

:040000 040000 e5fc20a8a722aa72314f80421b34cdba07d41d4c 12de9ece7073fec035599185cae8328b20828886 M    src

**Comment by edgardoh** [comment]
This should be fixed in current master, but the the profile must be re-selected.

**Comment by codingdave** [comment]
@edgardoh if you assume https://github.com/darktable-org/darktable/issues/2178 fixes this issue I can confirm you it does not. Which commit do you refer to?

**Comment by edgardoh** [comment]
I don't remember the commit, but I do remember the issue, did you try it on
current master?

**Comment by codingdave** [comment]
I tried 4 days ago.

**Comment by edgardoh** [comment]
Maybe I don't remember correctly, I don't have access now but I'll check
today.

**Comment by edgardoh** [comment]
My bad, this is fixed in #2319, yet to be merged.

@TurboGit , maybe the PR should be split, it has two different things anyway.

**Comment by TurboGit** [comment]
@edgardoh : yes, better to split it indeed!

**Comment by sergeG** [comment]
Are there plans to introduce the fix into 2.6 branch? 2.6 is still unusable for me since Nikon profiles are still fail.

**Comment by codingdave** [comment]
You can easily workaround this by shortening your profile name. If course
this will not work for of photos that reference the long profile...

sergeG <notifications@github.com> schrieb am Mo., 15. Apr. 2019, 14:42:

**Comment by sergeG** [comment]
> this will ot work for of photos that reference the long profile

I have thousands  of such photos. This is an extremely bad solution.
