### ISSUE TITLE
Lighttable: missing triangle indicator of hierarchical view

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2385]
**Is your feature request related to a problem? Please describe.**
I like the fresh look in git-master 2.7.0+992~g776fc7315-dirty

Now, when you have collapsed hierarchical styles, there is no more this little white triangle, which indicates there is something hidden. Just a list like all non-collapsed once as well.

**Describe the solution you'd like**
I'd like to see that triangle comes back or any other indicator, that there are collapsed styles

**Describe alternatives you've considered**
Can be any other indication, but should be in accordance to what users expect, by means, should be as similar as possible to what other software does.

**Comment by TurboGit** [comment]
Can you show a screenshot, I have those buttons on my side...

**Comment by TurboGit** [comment]
Also make sure you're not using a specific CSS.

**Comment by AxelG-DE** [comment]
I get crazy now.... my screenshot tool does not work by key-stroke. I can trigger it manually but than I cannot have shot of the open style menu :-(((( 
(I'll try later again, but didn't wanna let you wait)

I did nothing about CSS by my self actively.

Where can I do what, in such terms? only in darktablerc? I did't touch it with that respect

**Comment by AxelG-DE** [comment]
just now I installed the roboto font but it didn't update anyhting with regards to this issue....

**Comment by TurboGit** [comment]
This should be fixed in latest version.

**Comment by AxelG-DE** [comment]
@TurboGit 
Sorry Pascal, I tried, as long you mean Version +1047, I need to disagree. The triangles are still missing

Unfortunately yet again, my shortcuts for spectacle, the KDE screenshot tool do not work. Otherwise I would send you a screenshot....

So unless you talk about a more latest version than -1047, please re-open :blush: 

TNX
 Axel

**Comment by TurboGit** [comment]
This has been fixed in the elegrant theme. Are you using this theme?

**Comment by AxelG-DE** [comment]
@TurboGit 
yes in elegant it works. for the "normal" darktable theme, that is not envisaged?

**Comment by TurboGit** [comment]
This should be done now as I have made elegant theme inherit the standard theme and merged the necessary fix into the main css.

**Comment by AxelG-DE** [comment]
@TurboGit
thanks for all your contribution!
