### ISSUE TITLE
Styles in Export Module

### ISSUE THREAD

**Issue by RalfKerkhoff** [darktable-org/darktable#2543]
OS: KDE Neon with Plasma 5.15.5
QT Version: 5.12.0

Selecting a style applied on export is nearly impossible because:
The popup that opens has a black background and it looks to me that the text color is also black.

It is the only module where this happens. The styles module itself works fine.
The style button in the darkroom (below the image) works too - here I have a black background too, but a white font color.

Ralf

**Comment by Nilvus** [comment]
Which version of darktable ? A capture screen would also help to understand what you see.

**Comment by RalfKerkhoff** [comment]
Hi, 
Version is 2.6.2. 

It seems that it has something to do with the number of styles imported.

If I start with an empty database (folder darktable in .config deleted) and import only a few styles anything is fine.
If I import all of the styles I have (804) it looks like on the attached screenshot.

As said in my first post, in the darktable there is no problem with this fairly large number of styles.

Ralf

![Screenshot_20190509_162214](https://user-images.githubusercontent.com/11216400/57461284-01e57380-7277-11e9-8763-31f1b8ad3090.png)

**Comment by Nilvus** [comment]
Hi,
Maybe try to use the new hierarchical styles first, introduced on 2.6.2. You just use the pipe | as tags to make your hierarchy. That will reduce your length of list and be easier for you to use your list.
See last manual for more info on that.

Maybe that will correct for you this issue, waiting the real one is corrected (probably a gtk code to improve).

**Comment by Nilvus** [comment]
I just forgot to say that this is probably resolved in darktable 2.7 (development version) with the new UI. So I suggest you to close your issue by now, as hierarchical styles could help waiting the new major version with the new UI.

**Comment by RalfKerkhoff** [comment]
Hi,
I already tried the hierarchy - that does not solve the problem.
I have done a review on my styles and deleted some unused styles.

If it is solved in 2.7 I am fine with it.
Ralf
