### ISSUE TITLE
switching from darkroom to lighttable does not display current photo

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#2921]
When I switch from darkroom to lighttable, the current photo is not displayed.  The photos displayed are where I started working, not where I am currently.

I would expect to see the current/selected item visible.

openSUSE Tumbleweed 20190905
darktable-2.7.0~git1675.94549e1a4

**Comment by AlicVB** [comment]
Hmm...
I can't reproduce here. But it shouldn't happen, as I have fix it in master some month ago...
By any chance, do you use "zooming lighttable" layout in lighttable ?
Otherwise, how do you change images in darkroom ? with filmstrip, keyboard ?
Thanks

**Comment by ptilopteri** [comment]
I use lighttable/filemanager.  I seldom use or show filmstrip.  I use mostly keyboard and short cuts and mouse mostly only where cannot use keyboard.

I can run test situations if you can define situations.

tks

**Comment by AlicVB** [comment]
Ok, so let's try to track down what happen here...
1- does it *never* go to current photo, or just in certain cases ?
2- can you try this steps ?
- open a quite large collection in lighttable
- open a photo from the bottom of the view in darkroom
- staying in darkroom, switch to a photo after (one you are sure that it's not visible in the previous lighttable view)
- switch back to lighttable
- you should see that your last opened image is shown in the first row of lighttable view... Does it works for you ?

Thanks

**Comment by ptilopteri** [comment]
I normally have lighttable set to display 9 images.  If I switch to darkroom and back to lighttable and the current/selected image is one of those 9, the curent image is visible, otherwise not.  If I work more than 9 images, the current image will not be visible.

Large, my collections are usually >500 images.  Opening the lower right image (ninth on page) to darkroom from lighttable, advance one image and return to lighttable displays that image at the upper right of lighttable display.

But then starting with a photo displayed upper left in panel of 9 and working 31 images, returning to lightroom displays upper right the photo after the starting image.

Happy to attempt any scenario you wish.

tks

**Comment by ptilopteri** [comment]
closed by error :(

**Comment by ptilopteri** [comment]
fwiw: having a not rejected photo selected in lightroom and switching view parameters from "all" to "all except rejected" moves the "selected" image off lighttables display.  Also the reverse does the same, "all except rejected" to "all".

**Comment by AlicVB** [comment]
Ok, I've found the problem : only the first image switch is taken in account for resetting lighttable offset.
This should be fixed by PR #2940

**Comment by ptilopteri** [comment]
tks much, awaiting darix build for opensuse Tw                                                                                        │·
will confirm

**Comment by Smartich0ke** [comment]
despite this supposedly being fixed, I am still having this issue in 4.6.1.

**Comment by andreypz** [comment]
Hello,
I am using darktable 4.8.0 on Ubuntu 22.04 and I experience the same (or similar) problem.
When switching from darkroom to a  lightroom in the **culling layout**  mode I would expect the layout to start with the current photo from darkroom.  This does not happen. The photos in light table are the same as before.
