### ISSUE TITLE
Importing same folder twice and remove images from collection does not remove pics.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2983]
**Describe the bug**
Import pics using folder.
Again import pics using folder.
Now in lightable select all pics and hit delete key.
Confirmation dialog to remove pics from collection select yes.
Pics don't get removed.
Now select all a pics second time and repeat above steps for removing.
This time it removes them.

**Expected behavior**
Remove should remove all selected pics.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Win10
 - Version darktable-2.7.0+1804~g9819978c2-win64

**Comment by TurboGit** [comment]
Looks like a Windows specific issue. At least I cannot reproduce on Linux.

**Comment by chhil** [comment]
@TurboGit 
It happens after https://github.com/darktable-org/darktable/issues/2982

**Comment by leclercj** [comment]
I beleive this issue if now fixed with https://github.com/darktable-org/darktable/pull/2993 and can be closed

**Comment by chhil** [comment]
@leclercj Not fixed. I am on bleeding darktable-2.7.0+1859~gce84aeff9-win64

**Comment by chhil** [comment]
On a clean install and importing of images afresh  does not have this issue.

**Comment by TurboGit** [comment]
Ok, closing then.
