### ISSUE TITLE
Darktable creates artefacts on HDR images

### ISSUE THREAD

**Issue by KristijanZic** [darktable-org/darktable#3510]
**Describe the bug**
I've created an[ HDR dng image](https://drive.google.com/open?id=1XoDL4XEc0kklwBBNjG4eT2w8syqMNKcf) using [HDRMerge](https://jcelaya.github.io/hdrmerge/).
When imported in darktable the image preview is rendered with red, blue, yellow and white cross type artefacts. The same artefacts are also visible in the Darktable exported jpg image.

The raw dng [images for creating the HDR](https://drive.google.com/open?id=1Oec8SjmgBRmHUPnAwKqfoAioHQ_rr_vq) were captured using [5 AEB image stack](https://drive.google.com/open?id=1Oec8SjmgBRmHUPnAwKqfoAioHQ_rr_vq) on DJI Inspire 1 with Zenmuse X3 camera.

**To Reproduce**
1. open the [DJI_0096-0100_HDRM.dng](https://drive.google.com/open?id=1XoDL4XEc0kklwBBNjG4eT2w8syqMNKcf) in darktable darkroom.
2. Zoom in to see the artefacts clearer.

**Expected behavior**
The image should not be rendered with artefacts in the preview nor in the exported jpg.

**Screenshots**

![Screenshot from 2019-11-22 01-01-07](https://user-images.githubusercontent.com/10299892/69387371-eba87d80-0cc5-11ea-9350-b3efa5c11278.png)
![Screenshot from 2019-11-22 01-00-46](https://user-images.githubusercontent.com/10299892/69387386-f4994f00-0cc5-11ea-9d39-2751e2e0e95b.png)
![Screenshot from 2019-11-22 23-22-09](https://user-images.githubusercontent.com/10299892/69464749-80bb7d00-0d7f-11ea-81db-6db2c885cccc.png)

**Platform (please complete the following information):**
OS: Ubuntu 19.10 x86_64 
Host: Inspiron 13-7359 
Kernel: 5.3.0-23-generic 
Shell: bash 5.0.3 
Resolution: 1920x1080 
DE: GNOME 3.34.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-6500U (4) @ 3.100GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
Memory: 7818MiB 

Darktable Version: 3.0.0rc1~git44.9534ab08d && 2.6.2

**Additional context**
Rawtherapee doesn't have this issue
![Screenshot from 2019-11-22 22-38-48](https://user-images.githubusercontent.com/10299892/69462851-6501a800-0d7a-11ea-96bd-f78197dfa193.png)

**Comment by upegelow** [comment]
Hi,

looks like your HDR DNG file contains high number of pixels that cause the same effects like dead/stuck sensor cells within darktable. No idea about the exact nature of these pixels but probably they are kind of singularities that cause the demosaic algorithms to fail.

In darktable you can correct with the 'hot pixels' module. You need high settings for strength, though.

![Screenshot_20191122_082240](https://user-images.githubusercontent.com/1794020/69406027-65119180-0d01-11ea-8c07-79e082108ab2.png)

BTW, nothing special in 3.0 - the same effect is visible in the 2.6.x series.

**Comment by KristijanZic** [comment]
It's still a bug, only darktable gives this result and the individual images nor the HDR image don't have any hot or dead pixels.
Yes, that's why I've indicated that the issue is present both on 3.0 and 2.6.x.

**Comment by hellbuster** [comment]
@KristijanZic Which demosaic algorithm are you using?

**Comment by jenshannoschwalm** [comment]
These artefacts are clearly visible with all mosaicing methods. Also with passthrough, of course color smoothing reduces it but the problem remains.

![Bildschirmfoto von 2019-11-22 17-27-29](https://user-images.githubusercontent.com/50982232/69444430-9e252280-0d50-11ea-9864-5d091dc4648c.png)

I think this is a problem of the dng decoder (adobe deflated) @LebedevRI what do you think?

**Comment by LebedevRI** [comment]
I certainly agree that those do not seem to be introduced by dt modules,
but i'm unable to answer whether it is the decoding that is the issue here.
Do you observe the same in rawtherapee, etc?
What if you export from HDRMerge into some other format it supports exporting to?

**Comment by KristijanZic** [comment]
HDRMerge doesn't let me export to any other format.
Rawtherapee imports and renders it perfectly using any demosaicing algo.
![Screenshot from 2019-11-22 22-38-48](https://user-images.githubusercontent.com/10299892/69462377-199aca00-0d79-11ea-9b7e-172db8fcad90.png)

**Comment by LebedevRI** [comment]
Thanks for checking, that is an interesting data point.

**Comment by jenshannoschwalm** [comment]
I don't have access to those source images, in rawtherapee i see some areas with pixel artefacts but nothing like this. I screenshotted at 800% passthrough mode and cropped a region with certainly artefacts not always on the same channel.
![Bildschirmfoto von 2019-11-22 22-40-40](https://user-images.githubusercontent.com/50982232/69462761-2835b100-0d7a-11ea-9309-40a18936acaf.png)

Roughly the same region on rt doesn't show any hint of whatever "bayer mode" i use.
![Bildschirmfoto von 2019-11-22 22-44-47](https://user-images.githubusercontent.com/50982232/69463178-464fe100-0d7b-11ea-9503-27834208ffb1.png)
With a different blackpoint to make sure
![Bildschirmfoto von 2019-11-22 23-02-36](https://user-images.githubusercontent.com/50982232/69463619-5caa6c80-0d7c-11ea-996d-56feb4c6db68.png)

**Comment by KristijanZic** [comment]
I've provided everything when I opened the bug report and the images are here:
[https://drive.google.com/drive/folders/1Oec8SjmgBRmHUPnAwKqfoAioHQ_rr_vq](https://drive.google.com/drive/folders/1Oec8SjmgBRmHUPnAwKqfoAioHQ_rr_vq)

**Comment by jenshannoschwalm** [comment]
I think the problem is a this:

The merged dng file has an OpcodeList1 tag including FixBadPixels. This can be tested by either excluding the "correction" by disabling either
1. interpolateBadPixels
2. applyStage1DngOpcodes

If doing so the image in darktable looks just fine.

But where is the **real** problem? I took above images and extracted the OpcodeList1 by `exiftool -b -OpcodeList1`for DJI_0099.DNG and DJI_0096-0100_HDRM.DNG and was very surprised to see both list data to be identical. 

Looking into hdrmerge sources shows `void ExifTransfer::copyMetadata() {` in `hdrmerge/src/ExifTransfer.cpp` which does copyEXIF and this includes FixBadPixels. 


@LebedevRI i think this is nothing to be fixed in rawspeed (also not in dt), i simply concider this to be a hdrmerge issue. Agreed or do i misunderstand?

Or can we control this via a dt option?

**Comment by LebedevRI** [comment]
I'm not sure whether the problem is FixBadPixels in DNG OpcodeList1, but if i disable OpCode application altogether those pixels are no more. So i would agree that the problem is in HDRMerge.

**Comment by jenshannoschwalm** [comment]
@KristijanZic please close this issue as it has been fixed for a while.

**Comment by LebedevRI** [comment]
I believe this got fixed by 304f71e37e6658d804ba704230a224e7208f8ab4.

**Comment by KristijanZic** [comment]
I still don't see any difference when I open HDRMerged dng, still the same artefacts using the master.

**Comment by KristijanZic** [comment]
@jenshannoschwalm sorry, I wasn't checking the GitHub. I can confirm that the issue is fixed for me in master. Thank you all!
