### ISSUE TITLE
darktable 3.x.x segfault when zooming with feathering radius applied to a drawn mask on tone equalizer

### ISSUE THREAD

**Issue by blonchkman** [darktable-org/darktable#3927]
Dear developers,
First of all, I would like to thank you for the incredible progress made on version 3.

I'll share with you the behavior I encounter when applying a second softening guide on the tone equalizer module.

**Description:**
in the darkroom, zooming into an image when the tone equalizer is active with a feathering radius applied to a drawn mask causes a crash

**Steps to reproduce:**

1. Open a  blank raw in the darkroom
1. Activate the tone equalizer module (preset *fill-in*)
1. Draw a substantial shape (a simple circle is enough)
1. In the mask enhancement section, apply a softening radius (about 110).
1. Try zooming in to 100%, then 200%, then back to normal.

**Platform:**
 - Darktable version: 3.0.0+179~gcbca9efe9  (compiled)
 - Other impacted versions: 3.x.x (OBS bin or compiled)
 - OS: ubuntu 18.04, debian testing
 - [edit] i'm using nef raws
 
**Reproducible:** always

**Confirmed by others:** yes

**Comment by blonchkman** [comment]
I could observe that the crash also occurs with a parametric mask instead of a drawn one.

**Comment by jenshannoschwalm** [comment]
Might also be fixed by #3929

**Comment by blonchkman** [comment]
Hello @jenshannoschwalm ,
i noticed small changes in behavior after update to abb521d37ed7f68 (Robert Bridge's PR) but it still crashes. Now, i have to zoom in and back. Before, it crashed during zoom at 100%.

**Comment by junkyardsparkle** [comment]
I can reproduce this on a build from today. At a certain threshold of mask feathering radius, darktable segfaults on zoom, with `free(): invalid size` error.

**Comment by chhil** [comment]
Looks like the free vs  dt_free_align has bit us again.

https://github.com/darktable-org/darktable/pull/3955/files#diff-0

**Comment by blonchkman** [comment]
@chhil : thank you for your tip. I fetched the PR 3955 into a new branch in my 3.0.x tree, compiled and tested without noticeable change in behavior: it still segfaults. 

@jenshannoschwalm :  #3929 seems to have been merged into 3.0.x branch

**Comment by blonchkman** [comment]
**I wish you all a splendid year 2020.**

**Comment by Mark-64** [comment]
Same here.
Tone equalizer segfaults with any mask with feathering enabled when zooming in, even before reaching 100%
The part of the code where the segfault happens is
```
      if(!rois_equal && d->feathering_guide == DEVELOP_MASK_GUIDE_IN)
      {
        float *const guide_tmp = dt_alloc_align(64, sizeof(*guide_tmp) * buffsize * ch);
#ifdef _OPENMP
#pragma omp parallel for default(none) \
        dt_omp_firstprivate(ch, guide_tmp, ivoid, iwidth, oheight, owidth, xoffs, yoffs)
#endif
        for(size_t y = 0; y < oheight; y++)
        {
          size_t iindex = ((size_t)(y + yoffs) * iwidth + xoffs) * ch;
          size_t oindex = (size_t)(y + yoffs) * owidth * ch;
          memcpy(guide_tmp + oindex, (float *)ivoid + iindex, sizeof(*guide_tmp) * owidth * ch);
        }
        guide = guide_tmp;
      }
      guided_filter(guide, mask_bak, mask, owidth, oheight, ch, w, sqrt_eps, guide_weight, 0.f, 1.f);
      if(!rois_equal && d->feathering_guide == DEVELOP_MASK_GUIDE_IN) dt_free_align(guide);
      dt_free_align(mask_bak);
```
in blend.c from line 2996, when rois_equal is false.

**Comment by blonchkman** [comment]
Well done! Thank you very much for your action @Mark-64
