### ISSUE TITLE
UI Win 10: blinking text cursor non visible in empty text box

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#3940]
DT 3 git master on Windows 10
When clicking on any empty text box, the blinking cursor is not visible. 

![Cattura10](https://user-images.githubusercontent.com/43290988/71571817-82920200-2adc-11ea-912c-33a047024a17.JPG)

It appears when you start typing (or if the box has already text)

![Cattura11](https://user-images.githubusercontent.com/43290988/71571820-8756b600-2adc-11ea-9447-c385d0f61a64.JPG)

It is confusing because you don't know if the text box is active.

**Comment by Nilvus** [comment]
It's ok on Ubuntu 19.10 (Linux), OS I use so probably not CSS related and probably a specific Windows issue.

**Comment by Mark-64** [comment]
@Nilvus 
Agree that it's OK on Ubuntu (I use it as well).
However it is somewhat CSS related. What I found is the following:

1. In darktable.css, lines 162 and 226, I have to replace "sans-serif" with "sans". the former seems not to be recognized by Windows. Doing this, the cursor reappears in gtk-entry widgets even when start typing
2. However, if using another theme (which imports darktable.css) the above is not enough. For example in darktable-elegant-darker, I also have to leave only one font in the font-family statement in line 75. Leaving more that one font fails, even if the fonts works one by one. It seems to me that the issue [https://gitlab.gnome.org/GNOME/gtk/issues/1854](url) we discussed month ago is not yet solved, or at least not backported to MSYS2

Is there any way to make a css dependent on the OS used ? Or do we have to do different css for each OS?

**Comment by Nilvus** [comment]
@Mark-64 : not really CSS related. You just make confusion between issue and workaround. The workaround could be done with CSS but not solve the cause. Anyway, it has been solved in Gtk but maybe you not have the updated version on Windows. I don't use Windows so can't be more precise.

The font problem you describe have already been discussed and fixed in CSS. I don't say here that all is fix but that it has been fixed the better way it is possible in CSS. 

Of course, you could change fonts (just think that it means you not use Roboto fonts or system fonts by doing this workaround) but the only good way would be to have a Gtk version on Windows that's follow and use correctly font order.

Adding an OS CSS specific theme would be the same a workaround and will add an heavier stuff and work on darktable. That will mean cleaning them when for all it is fixed, having meantime a lot of users use the OS specific themes without understand why, one day, the behavior change or why one day we removed them because for all Gtk is ok. And how could we be sure for that.

So, having a css dependant theme here as a workaround is just a way to add more issues in the future.

A workaround is a user possibility not a code for all solution.

Last thing, this will probably solved in next weeks/months if a developer add a way to edit font and size in preferences instead of CSS. That has already been discussed. We now have to wait to see if a developer want to take time to work on this.

**Comment by Mark-64** [comment]
Fair enough, let's say mine is a workaround, not a solution:

![Cattura18](https://user-images.githubusercontent.com/43290988/71781717-eb441780-2fd1-11ea-8c6a-6d91fb0f201f.JPG)

The font fallback issue was supposed to be closed upstream 8 month ago, still it is not backported to my up-to-date MSYS2, and perhaps it will never be.
Also, I'm not sure that is the only problem; the fact that "sans-serif" has issues in Windows, but "sans" has not, might be a different thing.
Maybe one good day we will no longer need workarounds, until then I have to adapt my .css and perhaps they could be shared to other users in some "non-official way"

**Comment by Mark-64** [comment]
Update.
I was wrong about the backporting of the fix for font fallback issue in GTK. The font fallback now does work, I've tested it and it's 100% sure.
So this is a totally different issue, and it's weird.
In darktable.css, line 162, I have to put "sans" instead of "sans-serif", although "sans-serif" does exists in Windows and it is recognized, as Pango does not give warnings for "sans-serif", while it does if I put some other funny names.
In darktable-elegant-darker.css, first section from row 75, I have to put only one font family, although the fallback mechanism works as I said.
Failing to do one of the two tweaks above will have the effect of making the text cursor disappear, which is pretty annoying.
I attach the two modified .css files
[darktable-win.css.txt](https://github.com/darktable-org/darktable/files/4025250/darktable-win.css.txt)
[darktable-elegant-darker-win.css.txt](https://github.com/darktable-org/darktable/files/4025252/darktable-elegant-darker-win.css.txt)

**Comment by Mark-64** [comment]
Created bug report in Gtk+ 
[https://gitlab.gnome.org/GNOME/gtk/issues/2394](url)

**Comment by Nilvus** [comment]
@Mark-64: this issue is solved on Windows?

**Comment by coffeeandspaceships** [comment]
I can reproduce using the steps given in @Mark-64 's bug report to Gnome upstream.

I am using `3.24.16-1` which is slightly newer, but the problem is still there.

Nothing has happened to the upstream report in four months.

**Comment by Mark-64** [comment]
@Nilvus  No, it's not solved. 
It is not related to the font fallback bug, that has been solved long ago. It is more related to the font class names.
Replacing `sans-serif` with `sans` solves the issue in Windows, at least with darktable.css.
Unfortunately it has severe adverse effects in Linux. 
Is there any way to make OS-dependent statements in css ?

**Comment by johnny-bit** [comment]
My idea would be to have CMake replace 'sans-serif' with 'sans' when building for windows.

**Comment by Nilvus** [comment]
> @Nilvus No, it's not solved.
> It is not related to the font fallback bug, that has been solved long ago. It is more related to the font class names.
> Replacing `sans-serif` with `sans` solves the issue in Windows, at least with darktable.css.
> Unfortunately it has severe adverse effects in Linux.
> Is there any way to make OS-dependent statements in css ?

CSS is at first a style-sheet language for web pages, so it's possible to deal with different browsers but, unfortunately, not with OS.

Sans-serif is better to use and that issue is really strange (another Gtk one, like tooltip position #5348). 
If you think it's better with Sans on Windows, the condition to use Sans instead Sans-serif only in Windows should be set by code (as @johnny-bit suggest). I don't see another way here.
The risk to solve a Gtk issue with a workaround on darktable is that if/when Gtk issue will really be solved, the workaround will hide that.

**Comment by Nilvus** [comment]
Just a thought, font-family is a way to set default fonts to used by priority. darkable CSS default theme use at first OS font size and could go to a first Sans-serif one at first.

So, @Mark-64 and @coffeeandspaceships, could you test by just adding serif (separated by a comma) to that line (or in darktable.css, line 165, or in CSS editor in preferences (save CSS and check of course the checkbox above the text field. In CSS editor, just copy/paste that: 

```
*
{
  font-family: sans-serif, serif;
}
```

**Comment by parafin** [comment]
I think there is a bug in GTK with specifying several font families that causes crashes on macOS or something like that.

**Comment by Nilvus** [comment]
> I think there is a bug in GTK with specifying several font families that causes crashes on macOS or something like that.

As you are on macOS it would be good if you good just test that line on your side (in case of this line works for issue here on Windows).

**Comment by parafin** [comment]
I can try if I don't forget. But that bug seems to also depend on fonts installed...

**Comment by Mark-64** [comment]
Putting
```
*
{
  font-family: sans-serif, serif;
}
```
does not work, while putting
```
entry
{
  font-family: sans;
}

```
at the end of darktable.css does.
So maybe a workaround could be using that statement in the CSS editor.
Problem is that CSS editor does not work at all in Windows.
Digging in the code, the @import("path/to/css") statement contains drive letters in Windows which css doesn not like, plus maybe other quirks.
I am currently investigating this bug.

**Comment by Nilvus** [comment]
> I can try if I don't forget. But that bug seems to also depend on fonts installed...

Probably related to that yes. No need to test now as it doesn't work for @Mark-64 on Windows.

**Comment by Nilvus** [comment]
@Mark-64 and @parafin: I just see that I made a mistake on writing my line.

I would mean writing **sans** and not **serif** on font-family.

@Mark-64: could you test with that:
```

*
{
  font-family: sans-serif, sans;
}
```

**Comment by Nilvus** [comment]
> ```
> entry
> {
>   font-family: sans;
> }
> ```
> at the end of darktable.css does.
> So maybe a workaround could be using that statement in the CSS editor.
> Problem is that CSS editor does not work at all in Windows.
> Digging in the code, the `@import("path/to/css")` statement contains drive letters in Windows which css does not like, plus maybe other quirks.
> I am currently investigating this bug.

It's ok with that on default main theme on my side too (Ubuntu) but really not suitable for elegant themes. Did you check that on Windows? And maybe adding sans fonts near Roboto and elegant-darker theme would be suitable. Another thing to test.

But at last, I agree with @parafin: that bug is probably also related to fonts installed. And how Gtk on Windows handle them.

**Comment by Mark-64** [comment]
My report has been moved to pango
[https://gitlab.gnome.org/GNOME/pango/-/issues/482](url)

**Comment by Nilvus** [comment]
> My report has been moved to pango
> [https://gitlab.gnome.org/GNOME/pango/-/issues/482](url)

Ok, does that mean we could close this issue as it should be a pango issue?

**Comment by Mark-64** [comment]
Fixed user.css on Windows via #5440 
Adding in the editor
```
entry
{
  font-family: sans;
}
```
works now, at least for darktable.css. For the other themes I have to experiment.
Unfortunately putting more that one font in the same statement doesn't work either.
I believe there not so much more we can do here, but at least a partial workaround has been found.
I close
