### ISSUE TITLE
Default modules don't get always applied

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#4089]
**Describe the bug**

Even though I have selected to apply base curve and sharpening by default on new files, they can be missing from new images, see below.

**To Reproduce**

Session one -- Import a filmroll of virgin raw files. At this time all files will have got the default treatment: base curve, sharpening and so on. I can hit `W` to preview pics on the lighttable and get punchy previews (means that base curve has been applied as it should be).

Now, do subsequent sessions with other filmrolls. Go look at other filmrolls, close and open DT in between a few times. Now get back to the originally imported filmroll. Notice how base curve and sharpening are missing.

**Expected behavior**

The automatic defaults that were present during session #1 should remain applied.

**Platform (please complete the following information):**

 - Darktable Version: 3.0.0 built from gentoo portage
 - OS: gentoo linux
 - opencl 
 - geforce 1060 gtx + nvidia blob

**Additional context**

Two sidecars from the same picture. First one at 992 bytes is what darktable does when I import the directory the first time. The second one is when I opened the picture on darkroom. It is missing my defaults. 

The third one is a proper 5.7-kilobyte xmp that is the norm with my selected defaults. This xmp was created using the Duplicate manager / "create virgin duplicate" feature. 

[imported_once_not_opened.xmp.gz](https://github.com/darktable-org/darktable/files/4050502/imported_once_not_opened.xmp.gz)

[imported_once_opened_without_processing.xmp.gz](https://github.com/darktable-org/darktable/files/4050503/imported_once_opened_without_processing.xmp.gz)

[virgin_duplicate.xmp.gz](https://github.com/darktable-org/darktable/files/4050506/virgin_duplicate.xmp.gz)

**Comment by progo** [comment]
As a good workaround,

* have experimented developing pics without the base curve. Usually brings better control to the process, especially highlight control. But this is more work per image for sure. 
* on lighttable/history module, discarded histories in mass. This brings the defaults back.

**Comment by aurelienpierre** [comment]
Do you have a preset that disables the base curve automatically ?

**Comment by progo** [comment]
No such things. No presets or styles that touch the base curve, automatically or otherwise.

**Comment by aurelienpierre** [comment]
Ok, it seems you are not the only one. Probably something to do with pipe order management.

**Comment by jenshannoschwalm** [comment]
Hi @progo i think this should be fixed in master right now. Could you test your problem again and either close this issue or come back with fresh details...

**Comment by progo** [comment]
> Hi @progo i think this should be fixed in master right now. Could you test your problem again and either close this issue or come back with fresh details...

Thank you for your contribution!

Playing with master and 3.0.1, unfortunately right now I'm unable to repro the PROBLEM in either version so it's not possible to say if it's fixed for good.

I'm going to keep using the master version for now because it seems to run snappy... Of course if this version works correctly it's not exactly proving anything.

3.0.1 vs current master 3.1.0+1107~g08a09f74f

**Comment by jenshannoschwalm** [comment]
Please close this issue, re-open if you can again find anything you reported here. This would help devs to keep track on remaining/existing problems

**Comment by progo** [comment]
> Please close this issue, re-open if you can again find anything you reported here. This would help devs to keep track on remaining/existing problems

Done. 

Reading up on your PR your findings match exactly mine, namely darktable has generated sidecars with `darktable:auto_presets_applied="1"` yet their histories are empty. I'm confident your fix solved the issue.

**Comment by jenshannoschwalm** [comment]
@TurboGit You still have this as todo in projects pipe reordering ...

**Comment by TurboGit** [comment]
> @TurboGit You still have this as todo in projects pipe reordering ...

Sorry, what do you mean? This is fixed now, maybe I forgot something which is always possible...

**Comment by jenshannoschwalm** [comment]
In darktable projects you are collecting stuff and din't update the "to do" status
