### ISSUE TITLE
Presets in collect have swapped "tag" for "camera"

### ISSUE THREAD

**Issue by garrett** [darktable-org/darktable#4962]
**Description**

When using darktable built from master, selecting a previously stored "collect images" preset (in the lighttable) which previously had the "tag" filter now shows a "camera" filter (with the same text as before). Since the source is now "camera", the presets no longer work, unless manually updated.

(Did a database update or some code change cause the collect's sources to switch?)

The sources I've found that are problematic:

- tags (turns to "camera")
- date (turns to "lens")

Some, such as "film roll" seem fine. I guess there's some sort of a reference to IDs and those accidentally changed? Or the presets refer to an option's order, but the presets code wasn't updated accordingly?

**To Reproduce**
1. Go to the lighttable view
2. Click on the menu (☰)
3. Select a previously-created preset from darktable from a while ago (such as one made with stable, or even from a few weeks ago)
4. Notice that what was once "tag" is now "camera", so the search results are now empty

**Expected behavior**

Saved "collect images" presents should stay the same across darktable versions (and commits in master).

**Platform (please complete the following information):**
 - Darktable Version: git master, 3.1.0+1495~g022c2f1f0
 - OS: Linux, Fedora 32
 - OpenCL: Yes
 - Graphics: Intel(R) Gen9 HD Graphics NEO (OpenCL 2.1 NEO)

**Additional context**

- I compiled darktable myself, Using LLVM
- Compile options, according to `darktable --version`:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by TurboGit** [comment]
I understand what is going wrong...

We have re-ordered the collections to propose them properly grouped by theme. All dates, all metadata, all exif based information... etc. But the preferences are referencing the filters with a specific order! I'll see if this can be fixed.

**Comment by TurboGit** [comment]
Should be fixed, can you test again ?

**Comment by garrett** [comment]
Most seem to be fixed, however, a few are still wrong — but I am _pretty sure_ these are the ones I updated when sources were swapped. So they're swapped back (and wrong again). At least most seem right — I've only updated a few, thankfully.

It's easy enough to readjust the few ones I changed on my end, provided this is fixed for everyone. :wink:

Thanks for the quick fix!
