### ISSUE TITLE
Changing the image rating in filtered darkroom

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#5042]
Hi

**Describe the bug**
In the darkroom with filter, when I change rating of an image, it disappears from filmstrip, but remains editable, and the working focus does not switch to next image on the right in filmstrip.

**To Reproduce**
1. In darkroom to select a filter other than "all"
2. Change current image rating

**Expected behavior**
Focus in filmstrip must switch to next image on the right and it should be editable.

**Platform (please complete the following information):**
Darktable Version: master
OS: Debian 10

**Additional context**
It may be unrelated to this problem, but current image is not highlighted in filmstrip.

**Comment by Nilvus** [comment]
The filter is applied in filmstrip (that's the normal behavior) so depending on setting, the image could disappear but of course remains on darkroom if you don't ask darktable to change (shortcuts and click on images are here for that).

And which master you use (which commit)? The image is highlighted on my side (it should be since my CSS complete rework merged yesterday.

**Comment by esq4** [comment]
I use e26828239 ("prevent dynamic shortcuts giving keyboard focus to sliders", 2020-05-13).

Weird... I checked again: there really is a highlight in filmstrip. We will consider that this problem was successfully solved.

> ... the image could disappear but of course remains on darkroom if you don't ask darktable to change (shortcuts and click on images are here for that).

But in March or earlier it worked automatically. And it was convenient and unambiguous. And now I must not forget to do extra actions to edit the selected image but not a rejected image already.

**Comment by AlicVB** [comment]
I'm the one to blame for that.
That said, I'm not sure that changing the current behavior is a good idea. darkroom is for editing images, so I would find it weird if the image can disappear during an edit session.

If I want to do some culling, there's specific other mode for that...

**Comment by esq4** [comment]
Nothing strange. During editing, you came to the conclusion that the image is unpromising, you reject it and do not want to edit or see it anymore. But continuing to edit the rejected image is strange.

**Comment by rfeg** [comment]
(newbie here, please be tolerant)
Coming from years of lightroom (amateur) usage this one is one of the comments I have: IMO we should be able to have star rating AND reject flag, i.e. if I remove reject I get the rating (as it does in LR). Now when I reject I loose rating (ver 3.0.2 @ OSX 10.15.4)
Rational:
1. you are rating photos and you have 3 good candidates pics and you rate them 4 stars
2. you filter everything below 4 stars to focus
3. you think one has better composition than the others and reject the other two
4. you find out that focus is not perfect, so you want to go back to the second-best pic

with DT you have to find it on the rejected pile with no rating
with LR you filter 4 stars, remove the rejected filter and voila

Note: I don't want to transform DT in LR, I think is really useful.

**Comment by AlicVB** [comment]
@rfeg : already in master :) master is the current development branch that will be available in the next "big" dt version, usually around the end of the year

**Comment by rfeg** [comment]
@AlicVB thank you and sorry for not knowing it (newbie here trying to help). I'll start using master.

**Comment by esq4** [comment]
@AlicVB Looks like I don’t know how to explain. I will try again.

In DR there is the workspace and the filmstrip.

It seems logical to me that the image in the workspace is also present in the filmstrip. Or otherwise, in the workspace, I see only images from the collection in the filmstrip. When I change the rating of a image, it disappears from the filmstrip. And should disappear from the workspace.

If at the same time the next image in collection is AUTOMATICALLY selected, this will be excellent, this will be as before.

If only a gray field will displayed in the workspace, then this is not excellent, but at least acceptable: it is immediately clear that I have to MANUALLY select the next image in the collection.

Hope for understanding.

**Comment by Nilvus** [comment]
> It seems logical to me that the image in the workspace is also present in the filmstrip. Or otherwise, in the workspace, I see only images from the collection in the filmstrip. When I change the rating of a image, it disappears from the filmstrip. And should disappear from the workspace.

I will answer for this one. You could already have that. Just change filter on top of the "workspace" to all and you will not have this problem anymore. Think that filmstrip have the same behavior than lighttable (and it's needed as other users could have others way to work). Some users could find, sometime good to finish a work on an image without seeing the disappear, even if removed on filmstrip. So the filter is the way to go.

By the way, personally I think the best place to rate, keep or not, add color labels is the lighttable. But we all have different ways to work.

**Comment by esq4** [comment]
@Nilvus "...Some users ... sometime..." This is a good reason for breaking the functional.

@AlicVB  Still hope for understanding.

**Comment by Nilvus** [comment]
> @Nilvus "...Some users ... sometime..." This is a good reason for breaking the functional.

Because you think some and sometime means few. Of course not. How can I know all darktable users and how can you and me know how many? And why break something that other users want to keep for you? Maybe there's also some (few) users who want what you ask for.

You could ask for features you want but not forget that there's many others users and uses of a software. So, that's not means that a feature request will be follow. It can or not, depending on asking we have and, as it's a free software, if a developer is ready and ok to take of it's free time to develop it...

**Comment by esq4** [comment]
So I already ask.
And I am ready to help the developer to the best of my knowledge.

**Comment by AlicVB** [comment]
@esq4 : Thanks for your explanations. I'm sorry to say that there was no misunderstanding between us... and so my position doesn't change here. I really think that lighttable actions (and stars, colors, ...) should not interfere with the image editing when you are in darkroom.
For your specific use case (culling in editing phase) that will mean an extra step (press space) to go to next image.

Now there's the filmstrip. The filmstrip is here as a quick helper to avoid to go back to lighttable to do simple actions. Nothing more. I don't see any real problem to the fact that the currently edited image is not present in filmstrip... But I may have miss something...

**Comment by Nilvus** [comment]
> Now there's the filmstrip. The filmstrip is here as a quick helper to avoid to go back to lighttable to do simple actions. Nothing more. I don't see any real problem to the fact that the currently edited image is not present in filmstrip... But I may have miss something...

I don't think you miss something. I agree with you and that's why my answer and filter use mode if @esq4 want to have image remain on filmstrip when in workspace. The software already makes all he want by just a little adjustment. So no need to change the behavior as in actual state is good and useful.

I also don't see any problem here. So it's just here different view about that behavior.

**Comment by chhil** [comment]
This was fixed in https://github.com/darktable-org/darktable/issues/4539 did we regress?

**Comment by esq4** [comment]
> For your specific use case (culling in editing phase) that will mean an extra step (press space) to go to next image.

And  this doesn't work either.

**Comment by AlicVB** [comment]
> And this doesn't work either.

That's a bug, I'll fix it. Sorry to not have understand that point before...

**Comment by AlicVB** [comment]
Ok, so I've a fix for the accels in PR #5130 
Now for the other part, let's repeat my position : 

I really don't think it's a good idea to remove the currently edited image in darkroom because of some lighttable actions (rating in this case)

Now, I won't make any drama here if some other devs think the opposite ;) but we have to keep in mind that allowing that will have some strange side effect : 
for example one can have set aspect ratio tag in collect module. If we want to be consistent, and not to add exceptions in the code (I hate them) that means in this case, that your image may disappear from darkroom once you have cropped it. And I don't speak about some other collect tags like history, timestamps, ...

**Comment by TurboGit** [comment]
> I really don't think it's a good idea to remove the currently edited image in darkroom because of some lighttable actions (rating in this case)

I'm fine with this position. My previous question was because I thought this was the fixed issue in this PR. Frankly current behavior works for me.

**Comment by ptilopteri** [comment]
@AlicVB 

> I really don't think it's a good idea to remove the currently edited image in darkroom because of some lighttable actions (rating in this case)

but lighttable and darktable are separate and lighttable is an area where images are chosen to appear in darkroom, collections, sorted lists, ....  If I want to work on a group defined by >3 stars and I move to darktable with that group, then lower a particular image to 2 starts, I definitely do not want it to remain in the group I have in darkroom defined as >3 stars.  It definitely should be removed from the defined collection and not appear in that group in darkroom.  It no longer fits the parameters.  Being removed from the present collection in darkroom is the correct and expected action.

**Comment by AlicVB** [comment]
@ptilopteri : yes, and it's the case actually (look at the filmstrip) What I want to avoid is that the currently edited image may disappear because of that.

**Comment by ptilopteri** [comment]
@AlicVB 
I would expect the image to "disappear" if I was working in darkroom  on a collection of 3-star and changed the current image to 2 or 4 stars.  The same as if the current view was "all except rejected" and I rejected the image.

One has a defined collection working in darkroom and changes the current image to not be in the collection, one should expect it to disappear from view.

**Comment by esq4** [comment]
> Ok, so I've a fix for the accels in PR #5130

Yes, but filmstrip rewinds to the right and loses focus to the current image.

**Comment by AlicVB** [comment]
> Yes, but filmstrip rewinds to the right and loses focus to the current image.

Not sure to understand what you mean (sorry).
- At which moment does filmstrip rewind to the right ? when you reject the image or when you press an accel (and which one ?)
- what do you mean by lose focus ? the hover effect in filmstrip ? and same question : after the reject or after the next/previous accel ?

For the "disappearing", I'm not sure it's worth the pain to debate further. You have exposed your arguments, I've exposed mines and explain several times why it's not a good idea and why it can break if we go this way... Now let's hope someone in the future will comes with a genius idea (and code change) to conciliate the 2 points...

**Comment by esq4** [comment]
>     * At which moment does filmstrip rewind to the right ? when you reject the image or when you press an accel (and which one ?)

When I press space or backspace button.



>    * what do you mean by lose focus ? the hover effect in filmstrip ? and same question : after the reject or after the next/previous accel ?

Usually, after selecting image in filmstrip, it moves in the middle of window. Now, the first image in filmstrip is set in the middle of window, even if the last one has been activated.
 


> why it's not a good idea and why it can break if we go this way... Now let's hope someone in the future will comes with a genius idea (and code change) to conciliate the 2 points...

To be honest, I completely did not understand your explanation why it should break (:/), but I agree that we will have to wait for appearance of genius developer who will reconcile our views :)

**Comment by AlicVB** [comment]
@esq4 : got it. It should be fixed in PR #5173

**Comment by esq4** [comment]
Hmm, problem still exists. And moreover, pressing backspace button switches the focus to the next image in same way as space bar.
