### ISSUE TITLE
no such column: export_timestamp after upgrading 3.1.0 (commit 9ab4c8a9)

### ISSUE THREAD

**Issue by rgo** [darktable-org/darktable#5162]
**Describe the bug**
After upgrading darktable 3.1.0 from commit 7e9029ee4 version to commit b9ab4c8a9, I can load darktable but ligthtable is empty as you can see below

![image](https://user-images.githubusercontent.com/47124/82688630-7eb47700-9c59-11ea-8cc9-da744c75ceb8.png)

Checking the logs you can find this:

```
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:995, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT mi.id) FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/leptom/Pictures/2019/2019-01-06 Regalos Reyes'))) ORDER BY export_timestamp, print_timestamp , filename, version LIMIT ?1, ?2": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:999, function _dt_collection_compute_count(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1000, function _dt_collection_compute_count(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:995, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT mi.id) FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/leptom/Pictures/2019/2019-01-06 Regalos Reyes'))) ORDER BY export_timestamp, print_timestamp , filename, version LIMIT ?1, ?2": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:999, function _dt_collection_compute_count(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1000, function _dt_collection_compute_count(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1044, function dt_collection_get(), query "SELECT id FROM main.selected_images AS s JOIN (SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/leptom/Pictures/2019/2019-01-06 Regalos Reyes'))) ORDER BY export_timestamp, print_timestamp , filename, version LIMIT ?1, ?2) AS mi WHERE mi.id = s.imgid LIMIT -1, ?3": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1050, function dt_collection_get(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1051, function dt_collection_get(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1055, function dt_collection_get(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1981, function dt_collection_update_query(), query "DELETE FROM main.selected_images WHERE imgid NOT IN (SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/leptom/Pictures/2019/2019-01-06 Regalos Reyes'))) ORDER BY export_timestamp, print_timestamp , filename, version LIMIT ?1, ?2)": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1982, function dt_collection_update_query(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1983, function dt_collection_update_query(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:995, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT mi.id) FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/leptom/Pictures/2019/2019-01-06 Regalos Reyes'))) ORDER BY export_timestamp, print_timestamp , filename, version": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:995, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT mi.id) FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/leptom/Pictures/2019/2019-01-06 Regalos Reyes'))) ORDER BY export_timestamp, print_timestamp , filename, version": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1044, function dt_collection_get(), query "SELECT id FROM main.selected_images AS s JOIN (SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/leptom/Pictures/2019/2019-01-06 Regalos Reyes'))) ORDER BY export_timestamp, print_timestamp , filename, version) AS mi WHERE mi.id = s.imgid LIMIT -1, ?3": no such column: export_timestamp
...
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:172, function dt_collection_memory_update(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:173, function dt_collection_memory_update(): no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:995, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT mi.id) FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1) ORDER BY export_timestamp, print_timestamp , filename, version": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:995, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT mi.id) FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1) ORDER BY export_timestamp, print_timestamp , filename, version": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1044, function dt_collection_get(), query "SELECT id FROM main.selected_images AS s JOIN (SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1) ORDER BY export_timestamp, print_timestamp , filename, version) AS mi WHERE mi.id = s.imgid LIMIT -1, ?3": no such column: export_timestamp
sqlite3 error: /usr/src/packages/BUILD/src/common/collection.c:1055, function dt_collection_get(): no such column: export_timestamp

```

Database version is 30.

If I look into images table, export_timestamp exists:
```
sqlite> .schema images
CREATE TABLE IF NOT EXISTS "images" (id INTEGER PRIMARY KEY AUTOINCREMENT, group_id INTEGER, film_id INTEGER, width INTEGER, height INTEGER, filename VARCHAR, maker VARCHAR, model VARCHAR, lens VARCHAR, exposure REAL, aperture REAL, iso REAL, focal_length REAL, focus_distance REAL, datetime_taken CHAR(20), flags INTEGER, output_width INTEGER, output_height INTEGER, crop REAL, raw_parameters INTEGER, raw_denoise_threshold REAL, raw_auto_bright_threshold REAL, raw_black INTEGER, raw_maximum INTEGER, license VARCHAR, sha1sum CHAR(40), orientation INTEGER, histogram BLOB, lightmap BLOB, longitude REAL, latitude REAL, altitude REAL, color_matrix BLOB, colorspace INTEGER, version INTEGER, max_version INTEGER, write_timestamp INTEGER, history_end INTEGER, position INTEGER, aspect_ratio REAL, exposure_bias REAL, import_timestamp INTEGER DEFAULT -1, change_timestamp INTEGER DEFAULT -1, export_timestamp INTEGER DEFAULT -1, print_timestamp INTEGER DEFAULT -1);
CREATE INDEX images_group_id_index ON images (group_id);
CREATE INDEX images_film_id_index ON images (film_id);
CREATE INDEX images_filename_index ON images (filename);
CREATE INDEX image_position_index ON images (position);
```

darktable 3.1.0 files were obtained from OBS:
 - darktable_3.1.0~git1661.7e9029ee4_amd64.deb
 - darktable_3.1.0~git1727.b9ab4c8a9_amd64.deb

Based on these files, a problem was introduced between commit https://github.com/darktable-org/darktable/tree/7e9029ee4b29216933e7110a79df712a8a7e0233 and https://github.com/darktable-org/darktable/tree/b9ab4c8a9f6f899613ded3f1411106ef9763c218

**To Reproduce**
1. Install build 7e9029ee4
2. Upgrade to build b9ab4c8a9
3. Load darktable
4. Your lightable is empty
-->

**Expected behavior**
Once darktable is loaded, I expect to see my photos :)

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0
 - OS: Ubuntu 19.10
 - OpenCL enabled
 - amdgpupro 19.50.967956

**Additional context**
- Version compiled by OBS (https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable)

**Comment by TurboGit** [comment]
> Database version is 30.

Perfect !

> If I look into images table, export_timestamp exists:

Indeed, and the schema looks perfect too.

Have you somehow copied/moved your library ?

Anyway at this time I have no idea...

**Comment by TurboGit** [comment]
Ok, I have reproduced. This is when using `import date` into the collect module. There is no such error if you select say folder or filename. Do you confirm ?

I suspect a bug recently introduced by the work done by @phweyland. Philippe, can you have a look?

**Comment by phweyland** [comment]
> Philippe, can you have a look?

Yes, I'll do.

**Comment by phweyland** [comment]
I guess where the error in the code can be.
But I cannot reproduce the failure. There is something I don't understand. 
In the log above, the error comes in an request ordering by export_timestamp. But this is not an option in the sort by list. I've to find out how this does happen ...

**Comment by thokster** [comment]
I had the same here.
All empty with filmroll and directory.
Then I tried to collect by tag, everything fine.
Now everything works as expected (including filmroll and directory) an no more errors in the sql log.

**Comment by phweyland** [comment]
Ping @jpverrue. If you could help to find out where the user can select the option to sort by import_timestamp, ... Thanks

**Comment by phweyland** [comment]
I think I understand the issue. When adding the new time stamps some new sort codes have been introduced. So when dt starts and reads in darktablerc "plugins/collection/sort" it can get an old code (for example DT_COLLECTION_SORT_COLOR) which may correspond to the new DT_COLLECTION_SORT_EXPORT_TIMESTAMP code.
In this case we can have this strange behavior.

In the code I have not found anything which can set these sort codes (the 4 new ones).

> Then I tried to collect by tag, everything fine.
> Now everything works as expected (including filmroll and directory) an no more errors in the sql log.

This confirms the hypothesis above, as collecting by tag sets by default sorting (for tags) filename. This resets the unknown sort case. Afterwards everything runs well.

@TurboGit , So I think the fix is to remove the none used codes :
  DT_COLLECTION_SORT_IMPORT_TIMESTAMP,
  DT_COLLECTION_SORT_CHANGE_TIMESTAMP,
  DT_COLLECTION_SORT_EXPORT_TIMESTAMP,
  DT_COLLECTION_SORT_PRINT_TIMESTAMP,
unless there is some intention to add these entries in the sort by menu.

**Comment by phweyland** [comment]
More a comment to understand why the issue shows up with my last commit.

Before this commit, the collection query used `SELECT *` that I have changed to select only the required fields. The `images` table is very large and I think this is a weak design to retrieve all fields for potentially all images when some few fields are necessary ... (unless sqlite was able to optimize internally the query)

**Comment by jpverrue** [comment]
Of course there is a query optimiser in any SQL DBMS. But this table is not that big. I have known DBs where some tables had several hundred columns. This one has only about 40 columns.
On the other hand I don't understand why reading a column or all the columns would cause a sort order to fail, especially with an error on an unknown column. That's strange.

**Comment by phweyland** [comment]
> On the other hand I don't understand why reading a column or all the columns would cause a sort order to fail, especially with an error on an unknown column. That's strange.

As now the query gets specific fields, the ones which are used, if you try to use another one (like in SORT BY option) there is an error.




> Of course there is a query optimiser in any SQL DBMS.

Great! Would you have any info source showing how it works for sqlite ?

My original question to you was where these new sort codes are set, because I haven't found anything related to that.

**Comment by TurboGit** [comment]
@phweyland  : Ah indeed, makes sense. Those sort options have been added but they are not supported so we can remove them. We have collection based on those new timestamp but no sorting order for them.

Two options:

1. add sorting for DT_COLLECTION_SORT_*_TIMESTAMP
2. remove the definition and handling

?

**Comment by thokster** [comment]
> Now everything works as expected (including filmroll and directory) an no more errors in the sql log.

I must correct myself. There are still some cases that don't work properly and lighttable is empty (e.g. camera, lens, aperture, exposure.... and more)

**Comment by phweyland** [comment]
> I must correct myself. There are still some cases that don't work properly and lighttable is empty (e.g. camera, lens, aperture, exposure.... and more)

Yes, agreed. I have to fix those.

**Comment by jpverrue** [comment]
I found out what's going on. An order by clause can only work with columns in the select clause. Since you replaced the 'select *' with a 'select one_column' the necessary columns are no longer present and the select is analyzed as nonconforming. It would be necessary to 'reset select *'.

**Comment by jpverrue** [comment]
This is necessary because it could happen with any other column. Not just the new timestamp columns.

**Comment by phweyland** [comment]
> Here 'select *' is necessary.

That's the easy solution, I can agree with that. But that's not what I call necessary.

As the position field can come now either from images or from tagged_images, it is more difficult to use the select * option.

**Comment by jpverrue** [comment]
Yeah, all right. But in this case we must quote all the columns that are likely to be found in the order clause.

**Comment by rgo** [comment]
> > Here 'select *' is necessary.
> 
> That's the easy solution, I can agree with that. But that's not what I call necessary.
> 
> As the position field can come now either from images or from tagged_images, it is more difficult to use the select * option.

I've skim through it but we can select specific attributes from specific tables to avoid * if we know it in advance (sorry if it doesn't make sense).

**Comment by rgo** [comment]
> Ok, I have reproduced. This is when using `import date` into the collect module. There is no such error if you select say folder or filename. Do you confirm ?

I'll tell you later. I'm not sat at the right computer right now and also family matters.

**Comment by phweyland** [comment]
> I've skim through it but we can select specific attributes from specific tables to avoid * if we know it in advance (sorry if it doesn't make sense).

You are right. I've added the missing attributes. 


> Yeah, all right. But in this case we must quote all the columns that are likely to be found in the order clause.

yes,... and those necessary for collect filters. I'd missed these last ones, even if that's the order clause which has shown the issue.

> Two options:
> 
>     1. add sorting for DT_COLLECTION_SORT_*_TIMESTAMP
> 
>     2. remove the definition and handling

This is still open. @jpverrue, you may want to make the choice yourself.

**Comment by rgo** [comment]
> Ok, I have reproduced. This is when using `import date` into the collect module. There is no such error if you select say folder or filename. Do you confirm ?
> 
> I suspect a bug recently introduced by the work done by @phweyland. Philippe, can you have a look?

@TurboGit I was using film rolls, filter by one star or more and sort by color label.
After that, I tried with folders and other kinds randomly without success.

Now, I've changed to folders and sort by filename and it's working. It works also with my initial set up (film rolls, filter by one start or more and sort by color label).

**Comment by TurboGit** [comment]
Fixed.

**Comment by phweyland** [comment]
> > Two options:
> > ```
> > 1. add sorting for DT_COLLECTION_SORT_*_TIMESTAMP
> > 
> > 2. remove the definition and handling
> > ```
> 
> This is still open. @jpverrue, you may want to make the choice yourself.

This issue is still not solved. After upgrade to the new timestamp, the order which is displayed is not the one the has left before the upgrade (if sort by > time) if I'm not mistaken.

**Comment by ptilopteri** [comment]
confirmed, sort by time is different, doesn't seem to be using creation time stamp.  Maybe last access or last modified.

**Comment by ptilopteri** [comment]
@rgo 
@TurboGit 
@phweyland 
needs to be reopened
