### ISSUE TITLE
Fujifilm FinePix S1

### ISSUE THREAD

**Issue by bicknrown** [darktable-org/darktable#5633]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment]
Done.
I don't feel like updating rs submodule just yet, so for the moment you'll need to ensure that you checkout `develop` branch
in`src/external/rawspeed` submodule.

**Comment by bicknrown** [comment]
I am still seeing an issue where it can't read raws from the camera.

`RawSpeed:Unable to find camera in database: 'FUJIFILM' 'FinePix S1' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (DSCF5441.RAF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 174: Camera 'FUJIFILM' 'FinePix S1', mode '' not supported, and not allowed to guess. Sorry.` 

This was after building from the master branch in a clean installation environment of Manjaro 20.0.3.
I double checked the commits and they do line up, and the submodule for rawspeed is pulling from the `develop` branch. I might just be missing something obvious here, but if i'm not, let me know if there is anything else you need me to provide.

**Comment by LebedevRI** [comment]
> and the submodule for rawspeed is pulling from the `develop` branch.

But is the branch (at commit https://github.com/darktable-org/rawspeed/commit/6b7c1df2efd8df787787882361185003e1b2b9e0) actually checked out there?

**Comment by bicknrown** [comment]
It was not, I switched to the branch manually and it worked, thank you for the quick response.

I am curious though why in `.gitmodules` its labeled as the `develop` branch but checks out stable, or at least it looks like it is from what git says : `* (HEAD detached at 040ab75f)`

Anyway, thank you for your help!
