### ISSUE TITLE
DarkTable freezes when opening some files via "Open With..." from other apps

### ISSUE THREAD

**Issue by CrustyCurmudgeon** [darktable-org/darktable#6401]
Using Darktable with Digikam and XnViewMP under KDE linux (vers  & specs below). I usually open Darktable with a specific image file via the “Open With…” option from one of these apps. Recently DarkTable will terminally freezes upon opening and must be forcefully killed by the system. 

- This also happens when using the terminal command, as in “darktable /PATH/filename.tif”.
- This also happens when opening an image from Dolphin file manager using “Open With…”
- When I open DarkTable directly after this happens, the file(s) I tried to open are in the light table area (they were not imported prior to this.)
- DarkTable opens these images perfectly when I open the them manually from within the DarkTable app using “Import…Image” or from lighttable.
- My TIFFs are all 8-bit, ZIP compressed (deflate), and use the “TIF” extension (all lower case only). I’ve tried changing the extension to TIFF (lower case) with no change in DarkTable response.
- This happens occasionally (but less often) with other formats, JPG,NEF,RAW, so not exclusive to TIFF.
- This doesn’t happen when DarkTable is already open and an instance is running on the desktop; only when it's called from the “Open With…” dialogs and has to open a new instance.

Discussion on pixel.us darktable forum (https://discuss.pixls.us/t/darktable-freezes-when-opening-some-files/20480) indicates that this issue can be replicated with DarkTable v.3.2.1

**To Reproduce:**

1. Select a file in File Manager, or an  application, such as XnViewMP, Digikam, or GwenView
2. right-click and select "Open With... DarkTable"
3. DarkTable starts to open, then freezes with no error or subsequent response. 

**Expected Behavior:**

DarkTable should open the file in the Darkroom window.

**Additonal:**  
Complete removal and resinstall (with purge) has no effect.

**System Specs:**

OS: KDE Neon 20.04 focal Kernel: x86_64 Linux 5.4.0-47-generic
DE: KDE 5.74.0 / Plasma 5.19.5
CPU: AMD Ryzen 7 2700X Eight-Core @ 16x 3.7GHz
GPU: Radeon RX 570 Series (POLARIS10, DRM 3.35.0, 5.4.0-47-generic, LLVM 10.0.0)
RAM: 2432MiB / 32092MiB

**DarkTable specs:**
Version: 3.0.1
compile options:
    bit depth is 64 bit
    normal build
    SSE2 optimized codepath enabled
    OpenMP support enabled
    OpenCL support enabled
    Lua support enabled, API version 5.0.2
    Colord support enabled
    gPhoto2 support enabled
    GraphicsMagick support enabled
    OpenEXR support enabled

**Comment by jenshannoschwalm** [comment]
dt version 3.0.1 is really outdated, at least you should use the 3.2 version.
The bug you describe has been fixed in dt master a while ago (there also was an issue about it)

**Comment by CrustyCurmudgeon** [comment]
> dt version 3.0.1 is really outdated, at least you should use the 3.2 version.
> The bug you describe has been fixed in dt master a while ago (there also was an issue about it)

The thread at [here](https://discuss.pixls.us/t/darktable-freezes-when-opening-some-files/20480/4) would indicate the issue exists 
  in DT 3.2  under linux as well.

**Comment by jenshannoschwalm** [comment]
As i said, fixed in current master dt.

**Comment by jade-nl** [comment]
@jenshannoschwalm : This issue isn't fixed in latest master (darktable 3.3.0+919~g6248f38a9).

I did catch some terminal output that might come in handy (just the relevant parts):
```

ERROR in lualib, couldn't find a position for `script manager', this should never happen
blockdenom vanishes 
[image_cache_allocate] failed to open image 4294967295 from database: no more rows available
```

The symptoms are exactly the same as described using 3.0.1 and 3.2.1.

Some extra:

* Disabling opencl : Same result,
* Fresh darktablerc : Same result.

**Comment by ArJo45** [comment]
I experience the same issue when trying to open raw files from within Gimp. In my system I've found that lua seems to be causing the problem. If I rename my luarc file e.g. luarc.old the lua scripts are not loaded into darktable upon start up and the files open without any issue.
My system: Linux Mint 20 Cinnamon, GTX 1050 with proprietary Nvidia driver 450, Darktable 3.2.1.
Hope this can shed some light.

**Comment by johnny-bit** [comment]
@wpferguson - can you please take a look? It seems that there's still some lingering issue about...

**Comment by CrustyCurmudgeon** [comment]
Tested this morning after diabling OpenCL in ~/.config/darktable/darktablerc - no change in freeze behavior when opening image files (TIF,JPG) from Digikam via "Open with..." dialogue.

**Comment by CrustyCurmudgeon** [comment]
> I experience the same issue when trying to open raw files from within Gimp. In my system I've found that lua seems to be causing the problem. If I rename my luarc file e.g. luarc.old the lua scripts are not loaded into darktable upon start up and the files open without any issue.

I tried this today with no joy. Same behavior (DT freezes) when opening from Digikam via "Open with..."  dialogue.

**Comment by wpferguson** [comment]
I believe your lua scripts are out of date.  Try updating to the latest version and see if the problem persists.

In mid August I added a patch to all the scripts that create a module that checked to ensure the view was lighttable before trying to create the module, which was in response to this situation, or a situation similar.

**Comment by dim162** [comment]
With Xnview or Gimp from Darktable 3.3.0~git869.c5d05c948 & 3.2.1, i have no problem. But you need tu use native installer from the distribution for all 3 programs or "registered" them manually.

**Comment by ArJo45** [comment]
I just updated the lua scripts to the latest version and can indeed confirm that my issues have been solved. I can now open raw files from within Gimp.

**Comment by jade-nl** [comment]
Updating the the scripts did not solve the issue on my side.

Instead, or on top of, I had to remove the, somewhat large (775 lines, 24567 bytes), luarc script that is found in the configuration directory. After a restart this was replaced with a luarc with just one line (*require "tools/script_manager"*).

Problem is now solved.

**Comment by wpferguson** [comment]
@jade-nl the large luarc file was the script_manager script copied to the luarc file.  I also updated the README and changed the preferred luarc method to the one liner because it works in all situations across all platforms.

**Comment by jenshannoschwalm** [comment]
If we update from one dt version to another, how can we make sure the lua stuff gets updated too?

**Comment by wpferguson** [comment]
@jenshannoschwalm The lua scripts aren't tied to the darktable releases, nor are there formal releases.  

It does appear that we need to do a better job of getting the word out about bug fixes and recommended updates.  We could use the mailing lists and pixls.us and start publishing update recommendations and perhaps monthly status reports.

I'm working on a update to script_manager that will hopefully be out around the time of 3.4.  I plan on including the ability to check for update/update the scripts.

If you, or anyone else,  have any other ideas, I'd be happy to hear them.

**Comment by CrustyCurmudgeon** [comment]
> I believe your lua scripts are out of date. Try updating to the latest version and see if the problem persists.
> 
> In mid August I added a patch to all the scripts that create a module that checked to ensure the view was lighttable before trying to create the module, which was in response to this situation, or a situation similar.

I don't have any lua scripts  beyond the core installation; never used them. I did install the 3.2.1 DEB and it seems to be working okay. It still has a slight hesitation at the same point where it previously froze. It happens about 1 second after you see the DT session open and as the window is expanding to full size. That may be a glitch in the DE or the window manager.

At any rate, it seems to be  workign at the moment with DT  3.2.1 under KDE neon. Open from Digikam and XnViewMP are working fine.

**Comment by wpferguson** [comment]
@CrustyCurmudgeon since everyone appears to be working now, perhaps you would consider closing this issue?

**Comment by CrustyCurmudgeon** [comment]
Thanks, everyone!
