### ISSUE TITLE
memory leak in tone equalizer

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#6724]
Open your favorite top version/task manager.
In darkroom, go to the second tab of the tune equalizer module. Grab a node in the graph. Move the mouse up and down. Keep doing so as you see memory usage shoot through the roof.

I'm wondering if luminance, allocated with  dt_alloc_sse_ps(num_elem), ever gets released. But since the pointer gets passed around and there are buffered and unbuffered codepaths, I don't dare to make assumptions. Something for @aurelienpierre to take a look at?

"current" master on debian (no opencl) and windows (yes opencl).

**Comment by TurboGit** [comment]
I had a quick look, I'm not sure it is the luminance mask. But definitely a large memory leak to fix before the release.

**Comment by TurboGit** [comment]
I have pushed some fixes, it is lot better now but there is still some memory leak. Can you double check on your side that the situation is indeed better now ? TIA.

**Comment by dterrahe** [comment]
_Much_ better. To the point that I can't reliably increase memory use by moving around points on the curve in Tone Equalizer. Occasionally I still see jumps in memory use (that doesn't seem to be given back) but have not been able to discern reproduction steps and might be unrelated to this module.

Thanks!

**Comment by dterrahe** [comment]
Shall I close this or are there still possible issues you want to be reminded to look at?

**Comment by TurboGit** [comment]
I would close this as at this point I see nothing more to fix.

**Comment by dterrahe** [comment]
Great!
