### ISSUE TITLE
Select images on the map

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#7020]
**Problem**
In the map view it is possible to select images in the filmstrip, and the corresponding images on the map get highlighted with a white border (which is great!)

But it's not yet possible to do it the other way round :-(

Even worse: when single-clicking an image on the map, the image moves with the mouse-cursor
(which is only expected with click+drag)

So it happens quite often that I accidentally change the geo-position of images.

**Solution**
- selecting images on the map should select the corresponding files in the filmstrip

**Alternatives**
- no action when clicking on an image on the map
- show the same tooltip over images on the map as in the filmstrip

**Comment by Nilvus** [comment]
a duplicate (or similar) to #7000?

**Comment by quovadit** [comment]
No, they don't correlate, it's about selecting images in the map - 7000 is about filmstrip in darktable

**Comment by Nilvus** [comment]
> No, they don't correlate, it's about selecting images in the map - 7000 is about filmstrip in darktable

Oh, sorry, I've understood filmstrip in map here... So it's more a feature request here than an issue. Maybe @phweyland view would be good so.

**Comment by phweyland** [comment]
> when single-clicking an image on the map, the image moves with the mouse-cursor

This is an issue indeed. We have to increase probably the delay to decide this is drag. 

> But it's not yet possible to do it the other way round

I agree, it would be great to have some way to select images on the map itself. This is not completely straight forward and it could be useful to share ideas on this.
For an isolated image this is simple, but what about a group? And then, it would be probably useful to be able to select several thumbs... 
And then to be able to setup filmstrip with the current selection (this is related to collections)...
Thoughts?
I'm away from computer for some days. I'm afraid that won't be for 3.4.

**Comment by phweyland** [comment]
When #7124 is merged, it would be straight forward to do the following.
On mouse button release (if not a drag):
- click => select image
- shift-click => select images of clicked group
and maybe not too difficult :
- crtl-click or ctrl-shift-click add image or images of group to current selection.

@quovadit , would that answer the need ?

**Comment by phweyland** [comment]
Continue...
If the user clicks on a thumb he loses the current selection. That may be seen (or not) as a drawback. An alternative could be to use the right click instead of left click.

**Comment by quovadit** [comment]
In my opinion the selection of thumbnails should work the same in filmstrip and on the map.
Currently single click in filmstrip does not select an image, so you have to use Alt-Click (or Ctrl-Click to add it to selection).
There is a discussion in #7000 about this. Depending on the outcome, the same selection-methon should also be used on the map itself I think.

**Comment by phweyland** [comment]
> There is a discussion in #7000 about this.

Yes, but as you can see this new behaviour of filmstrip is not welcome for everybody...


> In my opinion the selection of thumbnails should work the same in filmstrip and on the map.

This is not the case of selection on lighttable ... I would this say that lighttable has a normal behaviour.

**Comment by quovadit** [comment]
I would also prefer to have the intuitive behavior back: single click selects, double click processes (in darkroom).
But in my opinion it's very important to be consistent. Having 2 different methods selecting thumbnails on 1 screen (!) would be weird.
But I agree that lighttable has the 'normal behavior', and I would really like it if this would be the case everywhere in darktable.

**Comment by Nilvus** [comment]
@quovadit: I totally agree to have a consistent way and so what @phweyland make here is good, normal behavior (like on lighttable and many software) and more intuitive way. The issue for images selection will just remain on filmstrip and so issue #7000.

**Comment by phweyland** [comment]
Starting point.
1. Currently the user can move images which are not in filmstrip and this is independent of the current selection on filmstrip.
2. The usage of selection on map is to ease the selection of images by position and to go back to lighttable and make some change on these selected images. I don't see any other usage. Am I right ?

Options.
1. Keep images movement  independent of selection. Then click and shift click cannot be used for selection. We can use as suggested above right-click to act on selection, but the is not particularly  intuitive and coherent.
2. Associate selection and movement of images, i.e. any image(s) drag is made on selection, as changing images order in lighttable. This intuitive but takes priority on filmstrip selected images. Remains the question of movement of images which are on the map but not on filmstrip. 
2.1. First option, we keep the current behaviour (letting the user select and move images on map but not on filmstrip). For this we need not to rely any more on dt_view_get_images_to_act_on() which limits the list of selected images to the current collection.
2.2. Second option, we don't let the user move images not present in filmstrip, which is not user friendly but let us use the dt_view_get_images_to_act_on() logic.

The 2.1. option has my preference for the time being. What do you think ?

**Comment by quovadit** [comment]
The usage I had in mind when opening this issue was the following:
I see a thumbnail on the map and want to know the name / date / containing folder of this image. So my intuitive behavior is hovering or clicking on it to get the information I want.

That's why I described the alternative:  "show the same tooltip over images on the map as in the filmstrip"

Meanwhile I think it could be dangerous to automatically sync selections of filmstrip and map, because of this scenario:
- I select all images in lighttable (for example to remove all color labels)
- then I open the map view
- I move one thumbnail on the map
- => all images change their position

Moving all images selected in the filmstrip would be a massive change to the current behavior without a visual hint.

So maybe it would be the best solution not to allow selection on the map?

Or: introduce a special multi-selection-mode:
- by default only the clicked image is selected (so only one image will move at once), but all images which are selected in the filmstrip get highlighted on the map (=current behavior)
- after chosing 'multi-select' all images selected in the filmstrip will be selected on the map. This selection can be changed as suggested (click replaces the selection, ctrl-click adds to the current selection). Dragging affects all selected images.
- in multi-selection-mode panning could also be replaced with drawing a rectangle to select all images in this region. 

If selection on the map is possible, I would also allow selecting images which are not present in filmstrip.

**Comment by phweyland** [comment]
> Meanwhile I think it could be dangerous to automatically sync selections of filmstrip and map, because of this scenario

Agreed, but ctrl-z works well. :)

This said, the need to select on map seems not to be your first priority and I still don't see a very strong use case on this. So we can wait for more feedback on this.

Getting image hovered information would be indeed interesting. I'll look at it.

**Comment by quovadit** [comment]
solved by #7137

**Comment by yushiyangk** [comment]
> solved by [#7137](https://github.com/darktable-org/darktable/pull/7137)

This does not solve it at all. #7137 is only useful for single images on the map; only information for the top-most image is shown for a stack.

Furthermore, this does nothing to help any further actions I might want to perform on the stack of images, such as updating their metadata. To do that, I would need *the images to be selected*, as described in the original issue.
