### ISSUE TITLE
Segfault on undo for module that does not support masks

### ISSUE THREAD

**Issue by paolodepetrillo** [darktable-org/darktable#7461]
To reproduce:
Make a change to a setting in any module which does not support masks.
Press Ctrl-Z and segfault occurs.

Undo does work normally in any module which does support masks.

The problem was introduced in commit db7ac22f. It does not segfault for the previous commit 3e0e655a.

**Comment by TurboGit** [comment]
Fixed in master and queued for 3.4.1. Thanks.

**Comment by paolodepetrillo** [comment]
It's still crashing, at a different line. This seems to fix it:

```
diff --git a/src/libs/history.c b/src/libs/history.c
index 5e1792996..345947a3e 100644
--- a/src/libs/history.c
+++ b/src/libs/history.c
@@ -655,8 +655,9 @@ static void _pop_undo(gpointer user_data, dt_undo_type_t type, dt_undo_data_t da
       darktable.develop->gui_module->request_mask_display = hist->request_mask_display;
       dt_iop_gui_update_blendif(darktable.develop->gui_module);
       dt_iop_gui_blend_data_t *bd = (dt_iop_gui_blend_data_t *)(dev->gui_module->blend_data);
-      dtgtk_button_set_active(DTGTK_BUTTON(bd->showmask),
-                              hist->request_mask_display == DT_DEV_PIXELPIPE_DISPLAY_MASK);
+      if(bd)
+        dtgtk_button_set_active(DTGTK_BUTTON(bd->showmask),
+                                hist->request_mask_display == DT_DEV_PIXELPIPE_DISPLAY_MASK);
     }
   }
 }
```

**Comment by TurboGit** [comment]
> It's still crashing, at a different line. This seems to fix it:

Makes lot of sense. Thanks, I will commit that soon.
