### ISSUE TITLE
Copying a style with more than one instance of given module breaks the image.

### ISSUE THREAD

**Issue by malewick** [darktable-org/darktable#7477]
When copying a style which includes more than one instance of the same module the image turns into a mosaic like this one (in both lighttable and darkroom):
![image](https://user-images.githubusercontent.com/24914567/103160132-b710ca80-47d1-11eb-9f83-e49750c1fb2a.png)

**To Reproduce (example)**
1. Edit one image using two instances of color balance.
2. Ctrl+C and Ctrl+V the style of the image onto another.
3. Observe chaos.

**Platform:**
 - Darktable Version: 3.4.0
 - Ubuntu 20.04.1 LTS

**Comment by johnny-bit** [comment]
Cannot replicate on 3.5.0+185 nor on 3.5.0+208. Haven't checked on 3.4.0 yet.

That being said - do you have OpenCL enabled? Any other modules involved except default ones + color balance?

**Comment by malewick** [comment]
Yes, OpenCL is enabled.
Below there's a screenshot with a list of enabled modules. Copied style had two instances of color balance and here in the image that the style was pasted on there is only one instance. History stack however shows that second instance.
It probably does't matter, but just for the record - these are .CR2 files from Canon 7D.
![image](https://user-images.githubusercontent.com/24914567/103170496-edd3f880-4844-11eb-8984-1ec801ced18e.png)

**Comment by johnny-bit** [comment]
Can you create a style out of that ad share? I'm testing on all kinds of raws and see no error with either disabled or enabled opencl... I'll reboot to check new drivers.

**Comment by malewick** [comment]
I've put the style file [here](https://drive.google.com/file/d/1NKoqgx8zWfCv3uNzl8_jGmI8d1aKtEwz/view?usp=sharing).
I checked and the bug appears also when applying the style.

**Comment by Nipsi** [comment]
Happens for me as well on 3.5.0~git208.3548ffb78, but only when the image is "untouched" by darktable, i.e. never opened in darkroom or with the history discarded before applying the style

### Untouched image
Image as imported from the camera or after discard history
![image](https://user-images.githubusercontent.com/8134686/103171053-6046d780-4849-11eb-9aaa-2d874f23cb9a.png)

Applying styles with only one instance per module works fine.
![image](https://user-images.githubusercontent.com/8134686/103171072-7eacd300-4849-11eb-8374-3b1aea9b29da.png)

Applying styles with two instances of the same module generates a pixely mess.
In this case 2 instances of tone equalizer.
![image](https://user-images.githubusercontent.com/8134686/103171042-4efdcb00-4849-11eb-82e0-f1f145beb7b3.png)
Switching to darkroom keeps the artifacts.
In the history stack both instances of tone equalizer are shown but the modules view on the right only shows one instance.
![image](https://user-images.githubusercontent.com/8134686/103171189-67bab080-484a-11eb-81d9-81383cceed51.png)
![image](https://user-images.githubusercontent.com/8134686/103171202-8751d900-484a-11eb-8808-b86759a40267.png)

Clicking on the first instance "tone equalizer" in the history stack makes the artifacts disappear.

### Image opened in darkroom after import or after discarding the history
everything works as expected with multiple instances of the same module

**Comment by johnny-bit** [comment]
Yeah. Now I can easily replicate. thanks for explaination @Nipsi!

@malewick - can you change/add `.txt` extension to the style file and attach it directly in the issue/post? Going through google drive is not optimal ;)

When applying style to virgin image or virgin duplicate here's what I get in the output (without even debugging enabled):

```
cannot get iop-order for colorbalance instance 1
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 56 (dt_dev_read_history_no_image end)
```
Playing around, walking through history etc gives me fun outputs:

```
cannot get iop-order for colorbalance instance 1
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 56 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
cannot get iop-order for colorbalance instance 1
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 56 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
cannot get iop-order for colorbalance instance 1
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 56 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! colorbalance 1(2147483647) image 0 (dt_dev_modules_update_multishow)
```

That tells me there's some initialization missing...

**Comment by johnny-bit** [comment]
Maybe onnected with #6734 ? Pinging @TurboGit here ;)

**Comment by TurboGit** [comment]
Yes probably something for me :)

**Comment by TurboGit** [comment]
Hum... There is something else I have cut&paste two instance of exposure or toneequalize without issue. I have then imported the style above (test_style) and applied it without issue. In all cases I have discarded the history.

**Comment by TurboGit** [comment]
Oh I see, I bet you are using the jpeg thumbs in preview and not the full RAW ? In that case indeed this is not XMP no dev done at all and so it breaks history.

We already have been discussing this issue. We may want to create the thumbs from the RAW before applying the style to ensure the dev is inited.

**Comment by malewick** [comment]
Yes, I was using jpeg thumbs and I confirm that when switching to half-size raw the problem disappears.

**Comment by TurboGit** [comment]
Should be fixed in master and will be part of 3.4.1.

**Comment by Sabilon** [comment]
Still an issue in 3.4.1 and 3.5.0~git1597.55c35574c, exactly as [described by @Nipsi ](https://github.com/darktable-org/darktable/issues/7477#issuecomment-751464461).

Note that:
- It does not depend on OpenCL begin enabled or disabled
- Nor it depends on JPEG / half RAW thumbnail setting.
- On real life scenarios, garbage can also happen after pasting a stack to an already processed image (and you're done with half a day work if you paste on dozens of images !)

@elstoc told me he would be kind enough to reopen :)

**Comment by Sabilon** [comment]
For anyone affected, there is a workaround (edited from [Nilvus comment](https://github.com/darktable-org/darktable/issues/8547#issuecomment-807267360) on a duplicate bug):
- duplicate corrupted image
- discard history on duplicated image
- get the duplicated image in and out of darkroom mode
- copy the history stack from the corrupted image to the duplicated one
- you can remove the corrupted image

**Comment by elstoc** [comment]
The last time I saw this issue was when I was working on the multi-instance module accelerators. It was caused by a module instance that had been pushed off the stack but was still being kept around in case it needed to be reinstated (`iop_order == INT_MAX`). The accelerators were still changing values on this out-of-pipe module and somehow it was still being incorrectly included in parts of the pipe calculation (I never got to the bottom of exactly how this was causing the image corruption).

**Comment by TurboGit** [comment]
I tried many different things to reproduce this and I cannot. I'll close. If you have a step by step reproducer just post here. And when I say step by step I really mean it as many things can be in play. For example how did you name the different instances, how the style was created (from lighttable or darkroom)? etc....
