### ISSUE TITLE
Darktable stile issue after upgrade to ver 3.4.0

### ISSUE THREAD

**Issue by MauDarktable** [darktable-org/darktable#7727]
**Describe the bug**

I all, after the upgrade to 3.4.0. version I've launched Darktable and found my Darktable GUI changed... please see 001.jpg attachment. If I change preferencies and restart Darktable I'm able to correct it, but after new start I have to re-do the procedure.

**To Reproduce**

Dont' know how reproduce, but I discover the problem at every new start of Darktable. I've changed some Darktable preferencies, please see the attachments.

**Expected behavior**

**Screenshots**

001.jpg - How I see Darktable GUI at new start
![001](https://user-images.githubusercontent.com/77062442/103867605-ec69c200-50c7-11eb-828d-bec9fa365f3d.jpg)
002.jgp - How I found my Darktable preferencies
![002](https://user-images.githubusercontent.com/77062442/103867608-ee338580-50c7-11eb-90f1-f44651622ec5.jpg)
003.jpg - How I changed my Darktable preferencies. Please take note to DPI and the flag regarding CSS
![003](https://user-images.githubusercontent.com/77062442/103867614-ef64b280-50c7-11eb-8dfc-a6eb8a5fee3f.jpg)
004.jpg - How the Darktable GUI have to be for me, this is the "correct" GUI.
![004](https://user-images.githubusercontent.com/77062442/103867617-f095df80-50c7-11eb-8c58-024b7bd6babc.jpg)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10 Pro 10.0.19042
 - 
 - 

**Additional context**

**Comment by MauDarktable** [comment]
Sorry, how can I attach my screenshots? I don't see any upload option... thanks.

**Comment by parafin** [comment]
Looks very similar to #7402, so they might be related.

**Comment by TurboGit** [comment]
In the CSS box I see:

`/* ...   /*`

Instead of
`
/*  ...  */`

**Comment by MauDarktable** [comment]
> /* ... */

Right! That's it! Thanks TurboGit, I think that could be an error in the italian version...

**Comment by TurboGit** [comment]
> I think that could be an error in the italian version...

Arg!!!! Indeed an issue in the translation, I have fixed it but this will probably be raising quite a lot of issues amongst Italian users.

**Comment by parafin** [comment]
I wonder why CSS override is enabled by default?..

**Comment by johnny-bit** [comment]
It shouldn't be...

**Comment by TurboGit** [comment]
Agreed it shouldn't but this is what is in darktableconfig.xml.in. I'll change that.

**Comment by TurboGit** [comment]
Done.

**Comment by pillo79** [comment]
Hello, just installed the latest Windows build (3.4.1.1) on a fresh Italian Windows 10 and had still the same issue (CSS override set and wrong CSS translation causing lots of chrome to disappear). Thanks for posting the solution - but can you verify why it is still shipped?
Thanks in advance!
