### ISSUE TITLE
[Censorize] DT core dump when input blur radius is changed.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#8266]
WSL Ubuntu 20

DT 3.5.0+1135

Stack trace when debugging using vscode (only thing I get in shell -> Floating point exception (core dumped))

```
libcensorize.so!process(struct dt_iop_module_t * self, dt_dev_pixelpipe_iop_t * piece, const void * const ivoid, void * const ovoid, const dt_iop_roi_t * const roi_in, const dt_iop_roi_t * const roi_out) (\home\mchhil\darktable\src\iop\censorize.c:151)
libdarktable.so!pixelpipe_process_on_CPU(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, float * input, dt_iop_buffer_dsc_t * input_format, const dt_iop_roi_t * roi_in, void ** output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, dt_iop_module_t * module, dt_dev_pixelpipe_iop_t * piece, dt_develop_tiling_t * tiling, dt_pixelpipe_flow_t * pixelpipe_flow) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1116)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:2006)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1342)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
```

![image](https://user-images.githubusercontent.com/1119439/108376413-fd5e3500-7228-11eb-9eef-ae12281ddc9e.png)

Based on variables, pixel_radius is 0, would result in divide by zero.

**Comment by johnny-bit** [comment]
For the life of me I cannot reproduce the problem.

Do you have reproducttion scenario for censorize module?

**Comment by chhil** [comment]
> For the life of me I cannot reproduce the problem.

And for the life of me, I can't reproduce it today. I used censorize on an image and it did its things.

But then I built it using `debug` build. On running it, on startup the image that I had cesorized was in `working` and I got the crash.
![image](https://user-images.githubusercontent.com/1119439/108622365-5531b180-745e-11eb-87af-89cfab855dc8.png)

**Comment by chhil** [comment]
Line 150 : ` const size_t pixel_radius = data->pixelate * roi_in->scale / piece->iscale;`

data->pixelate =0

**Comment by chhil** [comment]
Always reproducible on a debug build.

**Comment by chhil** [comment]
Additionally :

If I censorize with a releasewithdebug build. Then build using a debug only build.
Now I run it and on startup it crashes on censorize and the image that was censorized previously appears as
![image](https://user-images.githubusercontent.com/1119439/108623738-844c2100-7466-11eb-95a2-b4d918735034.png)


And debugger has stack trace where segfaul has occurred
```
libcensorize.so!process(struct dt_iop_module_t * self, dt_dev_pixelpipe_iop_t * piece, const void * const ivoid, void * const ovoid, const dt_iop_roi_t * const roi_in, const dt_iop_roi_t * const roi_out) (\home\mchhil\darktable\src\iop\censorize.c:151)
libdarktable.so!default_process(struct dt_iop_module_t * self, struct dt_dev_pixelpipe_iop_t * piece, const void * const i, void * const o, const struct dt_iop_roi_t * const roi_in, const struct dt_iop_roi_t * const roi_out) (\home\mchhil\darktable\src\develop\imageop.c:188)
libdarktable.so!pixelpipe_process_on_CPU(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, float * input, dt_iop_buffer_dsc_t * input_format, const dt_iop_roi_t * roi_in, void ** output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, dt_iop_module_t * module, dt_dev_pixelpipe_iop_t * piece, dt_develop_tiling_t * tiling, dt_pixelpipe_flow_t * pixelpipe_flow) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1116)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:2006)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1342)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, GList * pieces, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1213)

```

At this point I can never start DT. To work around this, I add 
`if (pixel_radius==0) return;`
This enables DT to run and I go in and reset censorize to be able to run DT through the debugger in the future and rebuild again with the line of code I added removed.

**Comment by chhil** [comment]
In releasewithdebug builds the breakpoint never gets hit, its probably optimized out, so it never crashes . 

![image](https://user-images.githubusercontent.com/1119439/108624370-a21b8500-746a-11eb-973a-f98bf4125c7c.png)

**Comment by phweyland** [comment]
> At this point I can never start DT. To work around this, I add
if (pixel_radius==0) return;

Looks like process () runs before gui_init() has set this parameter ... process() should not rely on ui data, should it ?

**Comment by TurboGit** [comment]
Ok, seems like there is a huge issue in censorize that I didn't spot will reviewing. There is no commit_params() and we have:

`typedef dt_iop_censorize_params_t dt_iop_censorize_data_t;`

Which seems plain wrong, or I'm missing something.

**Comment by TurboGit** [comment]
@chhil : Can you test #8294 ? TIA.

**Comment by chhil** [comment]
Sure, will test it tomorrow morning.

**Comment by TurboGit** [comment]
No need, what I have done is already was is done in the default commit_params() implementation. I have close the PR.

**Comment by johnny-bit** [comment]
@aurelienpierre can you take a look please?

**Comment by TurboGit** [comment]
But reading the code I see what could go wrong, the pixelate params is ranged between 0 and 500. If 0 we will also have the pixel_radius set to 0 and so a divide by 0.

**Comment by TurboGit** [comment]
Should be fixed by moving the declarations of pixels_x & pixels_y where used and in the section where pixel_radius is not 0.

**Comment by chhil** [comment]
@TurboGit 
This issue has been closed and its currently not fixed.

**Comment by chhil** [comment]
I can confirm that 

Adding the chane https://github.com/TurboGit/darktable/commit/8f207a2f74e20df640efb93a82c705640f28e627

and after moving  the following 2 lines 
```
  const size_t pixels_x = width / (2 * pixel_radius);
  const size_t pixels_y = height / (2 * pixel_radius);
```
inside the if block 

```
// pixelate
  if(pixel_radius != 0)
  {
```
I no longer get the crash.

**Comment by TurboGit** [comment]
So it is fixed finally ? You said in a message minutes before the last one that it was not ?

**Comment by chhil** [comment]
based on commits its not fixed.

> Should be fixed by moving the declarations of pixels_x & pixels_y where used and in the section where pixel_radius is not 0.

This was you indicating what will fix it.

I applied the code change of moving the 
 const size_t pixels_x = width / (2 * pixel_radius);
  const size_t pixels_y = height / (2 * pixel_radius);
inside the following if block

// pixelate
  if(pixel_radius != 0)
  {

This fixes it, but there is no PR that does the above code change.

**Comment by chhil** [comment]
I looked at the history of censorize. The change hash that moves  the consts inside the if check were not referenced in this ticket so I overlooked them. I am reverting my local changes, doing a fresh git pull and building.

**Comment by chhil** [comment]
I confirm the current master fixes the issue.


7cf38896d713fc989211e289951323174435e22a and d3cccabe8095b894b39050a32059269209fa5f14 fix the issue. Since the changes don't reference this issue, I missed out on incroporating those changes

**Comment by TurboGit** [comment]
Thanks for clarification!
