### ISSUE TITLE
Move selected images into special character path does not work (DT3.6.0.1 and DT3.7.0+601)

### ISSUE THREAD

**Issue by andreilabato** [darktable-org/darktable#9761]
**Did you buy darktable from an application store ?**=>NO

**Describe the bug/issue**
when I want to move images already loaded in DT, into a folder containing in the path a special character it does not work

**To Reproduce**
1. select one or several pictures
2. click on Selected Images menu (in lightable)=>Move...
3. chose a location with special character in the path
4. confirm
5. nothing happens

**Expected behavior**
images are moved into new collection

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.7.0+601_gf0e6c14fb
* OS                : windows 10 - 64b
* Memory            : 16,0 Go
* Graphics card     : y
* Graphics driver   : 
* OpenCL installed  : y
* OpenCL activated  : y
* Xorg              : 
* Desktop           : y
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version darktable-3.6.0.1-win64** no with version  darktable-3.4.1.1-win64 
 - Can you reproduce with a RAW or Jpeg or both? **both I assume but not tested**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Mark-64** [comment]
@andreilabato can you make me an example of path with special character?
I am currently working on improving file system support on Windows and I can try to include this fix too

**Comment by andreilabato** [comment]
@Mark-64 the issue is with my name (login) that contains s special character:
C:\Users\andré\Pictures

**Comment by domosbg** [comment]
@Mark-64 There is also a problem when you try to import pictures with the importing module if the import path contains german umlauts like ä, ö, ü. Darktable shows a message "x pictures imported", but the pictures are not added to the light table.

Is this related to the same problem as this issue here or should I create a new issue?

**Comment by andreilabato** [comment]
@Mark-64 the issue you mention is already known, and corrected in:
- DT 3.7.0+601_gf0e6c14fb (released)=> darktable windows insider program release=>https://discuss.pixls.us/t/darktable-windows-insider-program-8-1/26215?u=johnny-bit 
- DT 3.6.1 (not yet released)

**Comment by domosbg** [comment]
Yes, i can also confirm it. I tried 3.7.0+684~g40421d57d and everything works fine.
Thanks a lot for fixing.

**Comment by domosbg** [comment]
This issue can be closed or something is still not working? I tried to move pictures to a path with special characters as described in the first post. With 3.7.0+684 it is working.

**Comment by andreilabato** [comment]
@domosbg how can I get 3.7.0+684? 
Can I get it fom insider? 
- darktable windows insider program 8/15?
- darktable windows insider program 8/8?

**Comment by johnny-bit** [comment]
@andreilabato - any insider should have it fixed. 8/15 is the newest one, i bet today's next insider is comming :)

**Comment by andreilabato** [comment]
@domosbg 
tester insider program 8/22=>works fine with darktable-3.7.0+799_gd5556228e-win64 => copy, move and delete with folder with special character.

**Comment by johnny-bit** [comment]
I think the issue is fixed in both master and 3.6.1 release(coming soon)... Do you think we can close this issue?

**Comment by andreilabato** [comment]
yes thanks
