### ISSUE TITLE
Panasonic DC-S5 noise profiles

### ISSUE THREAD

**Issue by jdneumeyer77** [darktable-org/darktable#9791]
I've created noise profiles for the Panasonic S5. I've tried the presents with the noise images and they seem great. 

Not sure if it matters, but I had an overhead light on and there is brown in the left corner of the images, but it didn't affect the shades of gray or white stripe. Maybe there needs some clarity around one part of the tutorial stating to not turn off all of the lights in the dark room. The script wouldn't accept those.

With the new color calibration module how valuable are the white balance images?

Attached is the archive file.
[darktable-noiseprofile-20210810.tar.gz](https://github.com/darktable-org/darktable/files/6965809/darktable-noiseprofile-20210810.tar.gz)

**Comment by jdneumeyer77** [comment]
I probably have to redo these once #9811 is fixed don't I @johnny-bit?

**Comment by johnny-bit** [comment]
> I probably have to redo these once #9811 is fixed don't I

Most likely. I haven't checked your profiles but #9811 seems likely to have large impact on channel data.

**Comment by jdneumeyer77** [comment]
@johnny-bit 

Now that #9811 has been fixed. I've redone the noise profiles. As my fix affected pretty much all Panasonic cameras black levels, hopefully it doesn't affect their noise profiles too much... I've ensured my new build of DT had my fix and disabled my auto-preset workaround for black levels. Then I reran the script against the same sample files. So you should be able to directly compare the new upload with the old if that's helpful.

Happy to create an PR to add the presets if everything looks good.

[darktable-noiseprofile-20210907.tar.gz](https://github.com/darktable-org/darktable/files/7125400/darktable-noiseprofile-20210907.tar.gz)

**Comment by johnny-bit** [comment]
Well, TBH I still can't read those ;) If it's "good" profile then do a PR plz :)

**Comment by jdneumeyer77** [comment]
@johnny-bit no worries. They do seem archaic to understand even with the pretty graphs. I'll add a PR once I get a chance.
